#+STARTUP: showall

* EU Law

** 2022-10-05 - Classical reading of art. 4 TEU

*** Principle of conferral

- International organizations: must act within their mandate.
- Principle of conferral: is judicially enforceable (not just a reassurance for MS), and applied in a strict manner.
- "Competences not conferred": negative wording prevents expansion of EU competences.

*** Equality of MS

- Equality: MS are equal before the Treaties and in their national identities.
- Principle of mutual trust: it's an unwritten principle related to equality, EU law must be applied in the same manner to everyone.
- Differentiated treatment: inequalities due to new States acceding to the Union must be limited in duration, it's possible to treat some MS differently with enhanced cooperation, or opt-outs.
- Costa v. ENEL: MS can't take unilateral measures that violate EU law.

*** Principle of solidarity

- Principle of negative solidarity: MS must abstain from acts that violate the balance between the EU and MS, and undermine the mutual trust between MS.
- Principle of positive solidarity: applies to certain policies (terrorist attacks, asylum policies, stability of the Euro area), it's just an abstract principle that can't be enforced by itself, and must be implemented in concrete policies.

*** Principle of mutual trust

- Mutual trust: the Union's founding values are recognized by all MS, and that MS comply with EU law and respect fundamental rights.
- Consequence: MS don't have to check another MS' compliance with EU law.
- Principle of mutual recognition: closely connected with the principle of mutual trust, is applied in the free movement of goods, the internal market in general, and the principle of judicial protection.

*** National identities clause

- National identity: must be respected by the EU, is used frequently to block the adoption of EU acts.
- Counter-limits doctrine: EU law stops prevailing if it affects the integrity of the fundamental internal order.
- Definition of national identity: MS' supreme courts are in the best position to recognize their national identity.
- National security: is the exclusive concern of MS.
- National identity includes a MS's political and constitutional structures, including the regional and local level.
- MS can't rely on this clause in order to not apply EU law, and it doesn't create an obligation on the EU to prioritize national interests over Union ones.
- German constitutional court: EU law can be reviewed to make sure it doesn't harm the core constitutional values and takes away Statehood.
- The normal national identities review (art. 4(2) TEU) balances national and Union interests, the German constitutional court's proposed review is different and aims to protect the core of the German constitution.

*** Principle of loyalty or sincere cooperation

- Definition: MS and institutions should assist each other in achieving EU objectives, ensure their fulfillment, and refrain from measures that go against them.
- Analogies: "pacta sunt servanda" principle in international law, principle of cooperation in federal States.
- It's the most important principle in EU law, and according to the Court it would apply even if it wasn't explicitly stated.
- It can be applied only if there aren't specific provisions, but several provisions are a specification of the principle of loyalty.
- Originally it was considered a mere statement of political intentions, but later the Court recognized it as a source of obligations.
- MOX Plant case: Ireland breached the principle of loyalty because it challenged England before an international arbitration body without consulting with the EU institutions.
- Infringement proceedings: if Commissions requests are unclear the MS must ask for clarification, instead of using it as an excuse to continue infringing EU law.
- Regulations and directives: the MS and Commission must act in good faith to overcome issues.

*** Addressees of loyalty

- Horizontal loyalty: between MS.
- Vertical loyalty: all authorities in a MS are subject to loyalty towards the EU, including the judiciary, except for purely political matters, where MS are not required to cooperate with the Council or prioritize Union interests over national ones.
- Reverse-vertical loyalty: EU institutions must also cooperate with MS, in a mutual manner.

*** Functions of loyalty

- Constitutionalization: the principle of loyalty was used to justify the principle of primacy, direct and indirect effect, MS liability for violating EU law.
- Conflict prevention: States must refrain from acting in a way that would jeopardize the attainment of Union objectives.
- Cooperation: especially in mixed agreements.
- Compliance: MS must grant effective judicial protection for rights derived from EU law, introduce sanctions for breaches of EU law, nullify the consequences of a breach of EU law, amend national law that contrasts with EU law.

** 2022-10-06 - Principle of sincere cooperation and art. 4 TEU

*** Screening of FDI

- Background: due to the high degree of integration in the EU, FDI in one MS can affect the others, or the EU as a whole.
- Framework: MS can exchange information and raise concerns, the Commission can issue opinions when an investment can threaten the security and public order of a MS or undermine a EU project.
- National screening mechanisms: are subject to requirements, MS ultimately decide whether to approve an investment or not.
- Principle of sincere cooperation: the EU framework doesn't prejudice the MS' responsibility to safeguard their national security, MS should give due consideration to comments from other MS or the Commission.

*** Refugee crisis

- Dublin Regulation: adopted to deal with the 2015 refugee crisis, establishes the "State of first entry" criterion for processing requests, later MS agreed to distribute applications among MS.
- Some States decided not to implement the regulation as a matter of protecting national security, which is an exclusive prerogative of MS and can't be reviewed by the Court.
- EUCJ states that national security can't be abused as a general reservation in order not to implement EU law, and the principle of loyalty should prevail in this case.
- AG's opinion: solidarity is a fundamental value, MS must shoulder collective responsibilities and shouldn't base their actions on a mere cost-benefit analysis.

*** Wittgenstein case

- Real estate agent: is adopted by a German nobleman, and gains a noble title.
- Austria: has a constitutional law that abolished the use of noble titles, doesn't recognize the agent's noble title.
- Agent: now has a different name in Austria and Germany, which lead to a restriction of her freedom of movement.
- Austria: justifies the restriction on the basis of their national identity and public policy, which is possible, but should be interpreted strictly.
- Objective of the law: implement the more general principle of equality of all Austrian citizens before the law, which is also a fundamental EU principle.
- Conclusion: the justification is acceptable.

** EU institutions (2022-11-10)

*** Introduction

- Principles in art. 13 TEU: consistency, effectiveness, conferral, sincere cooperation.
- Contrast between effectiveness and representative democracy.
- Differentiation in procedural rules, institutional balance.

*** European Council

- Became an official institution with the Treaty of Lisbon (70).
- Composition: heads of State (with executive functions), heads of government.
- Can Sanction states (art. 7(2) TEU).
- No legislative functions, but can influence legislation (deadlines, guidelines) (71).
- Political decisions (composition and functioning for other institutions, set own agenda and functioning, accession procedure) (71, 72).
- President: organizes the European Council's work, ensures consensus, reports to the Parliament, represents the EU without prejudice for the High Representative (68).

*** Council

- Role: main decision-making organ, shares the role with the European Parliament (58).
- Composition: ministers from the MS' governments.
- Not to be confused with the European Coucil, composed of the presidents and prime ministers (58).
- Can be considered the Senate in the parliament of a federal State, but also has executive powers (58).
- Composition depends on the subject matter being discussed, there are various configurations that meet periodically (59).
- Legislative powers: in the ordinary legislative procedure it has the same role as the European Parliament, but in the special legislative procedure it can adopt legislation by only consulting the parliament.
- Policy-making and coordinating functions: TODO.
- International treaties: 
- COREPER

*** President of the EU

*** EU Parliament

- EU citizens can elect or be elected into the EU Parliament.
- No common electoral law.
- Electoral procedure to prevent biases
- Prohibition to hold multiple parliament seats
- Inquiry committees to check on the implementation of EU law

*** EU Commission

- Purpose: promote the interests of the EU
- Commissioners: number, appointment
- Organized like a government, but has no executive power
- Powers: propose legislation, law enforcement, anti-trust enforcement, representation

*** EU representation

- President of the European Council, president of the Commission, High Representative

** 2022-11-14

*** European Central Bank

- Technical institution, controls inflation
- Competence over the MS who use the Euro, can take binding decisions, subject to the scrutiny of the EUCJ
- Composition
- Executive committee

*** EU-Turkey statement

** 2022-11-16

*** TODO: Outright Monetary Transactions

*** EU competences

- Principle of conferral: MS confer competences to the EU to attain common objectives, the competences not conferred remain with the MS, the institutions of the EU must act within the powers conferred by the Treaties (110, 111).
- Division of competences: the competences can be exclusive, shared or supporting (113).
- The EU doesn't have the competence to give itself further competences, new powers always require a Treaty revision.
- Vertical division of powers: the Union must empowered to take any measure, both binding and non-binding.
- Horizontal division of powers: any Union measure must respect the limit and procedures in the Treaty.
- Institutional balance: the institutions in the EU must respect the division of powers.
- Implied powers: if Treaty articles confer a certain task to an institution, without specifying the powers that should be conferred, in order to make that provision effective, the powers are implied.
- Judicial review: the Court of Justice declares measures that violate the principle of conferral invalid, national supreme courts can review EU measures too and declare that they are ultra vires.

*** Exclusive competences

- "Exclusive": only the Union can adopt legally binding acts, and States may only be authorized to adopt implementing measures (113).
- Urgent measures: if the EU fails to adopt measures, MS can consult the Council in order to protect the common interests.
- Exhaustive list: includes the customs union, competition rules for the internal market, monetary policy for the Euro.

*** Shared competences

- Shared competences: if a competence isn't listed as exclusive or supporting, it's presumed to be shared in character, the list is non-exhaustive (114), they represent the majority of competences.
- Preemption: if the EU adopts rules on a certain matter, MS can no longer legislate on the specific elements the EU has regulated (the preemption doesn't apply to the whole area).
- Limitations: some fields are completely excluded from preemption, and in certain areas the EU only sets minimum standards (115).

*** Supporting competences

- "Supporting": the EU promotes cooperation in the action of MS, without binding effects.
- Scope: matters that are too close to national interests or identity, or too politically sensitive (115).

*** Common Foreign and Security Policy

- CFSP: legislation is excluded, and guidelines and cooperation is used instead.
- Intergovernmentalism: policies are defined and implemented by the European Council.
- Judicial review: is generally excluded, save for restrictive measures against natural or legal persons adopted by the CFSP, and to ensure that CFSP measures aren't used in competences under the general regime (116).

*** Subsidiarity

- Scope: only to non-exclusive competences.
- Definition: powers should be attributed to the level of government where it can be exercised most effectively.
- Purpose: balances centralization and the MS' sovereignty, can be used for ex ante and ex post review.
- Necessity test: the objectives can't be achieved by individual MS at their national, regional or local level.
- Added value test: Union action can achieve those objectives, unless it's shown that the objectives can be better achieved using international law (118).
- Acts must contain a detailed statement on the principle of subsidiarity, in order to facilitate its judicial review.

*** Proportionality

- Definition: EU action must be suitable to achieve an objective, and not go beyond what is necessary to achieve it.
- Choice between measures: the least onerous measure should be taken, and disadvantages can't be disproportionate to benefits.
- Discretion: the legislature enjoys wide discretion, and legality is affected only if the measure is manifestly inappropriate.
- Limits to discretion: choices must be based on objective criteria, and discretionary power is exercised following guidelines.

** 2022-11-17

*** International law sources

- Jus cogens: is recognized by the VCLT, refers to general rules that are at the top of the hierarchy, and can only be derogated by another piece of just cogens.
- Customs: are binding for all subjects of international law.
- Conventions: are binding and prevail over customs, but only between signing parties.
- Decisions: can be taken on the basis of treaties.
- Soft law: isn't binding, is used when the States are unable to agree on a binding instrument.

*** EU law sources

- Primary law: includes the Treaties, the Charter of Fundamental Rights, and the general principles developed by the EUCJ (108).
- Treaties: define the institutional framework of the EU, describe competences and powers, define the amendment procedure, the accession procedure, and various protocols.
- General principles of law: they're developed by the case law of the EUCJ, and can draw on common constitutional traditions among MS.
- Human rights: their protection is considered a general principle, originally they weren't considered because Treaties were purely economic in nature.
- International agreements: concluded with non-EU countries or international organizations.
- Secondary law: can be adopted by the Commission (and in specific cases, Council) in the conditions laid down in the Treaties or other secondary law.
- Binding secondary law: regulations, directives, decisions.
- Non-binding secondary law: opinions, recommendations, other soft law instruments.
- Hierarchy: secondary law must comply with primary law and international agreements, failing that the act is ultra vires and can be annulled (109).

*** Treaty revision

- Treaties can be amended using the ordinary or simplified procedures.
- The ordinary procedure has two stages, the first of which (the Convention) is optional, and the second is the intergovernmental one.

*** Ordinary revision procedure

- Scope: unrestricted, but unlikely to be used if a less cumbersome procedure is applicable.
- Initiative: amendments can be proposed by the European Parliament, Commission, any MS government, and are notified to national parliaments.
- European Council: consults with the Parliament, Commission, the ECB (if the amendments concern the monetary policy), and decides by a simple majority if the procedure should continue.
- Convention: is composed of representatives from national parliaments, the heads of State or government, the European Parliament and the Commission, and adopts decisions by consensus.
- Intergovernmental stage: a conference of representatives of the MS' governments adopts the amendments.
- Ratification: the adopted amendments have to be ratified by the MS' parliaments.
- Simplified variant: the European Council, with the consent of the European Parliament, can skip the Convention stage, if the amendments are limited in scope (144, 145).

** 2022-11-21

*** Special revision procedures

- Scope: limited to Part Three of the TFEU (policy areas of the EU), can't be used to increase competences.
- European Council: decides unanimously on the amendments, after consulting with the Commission, Parliament, and ECB (for institutional changes in the monetary area).
- Ratification: by all the MS is still necessary.
- European Stability Mechanism: has been introduced using this procedure.

*** Limitations on the amendment of treaties

- Defrenne case: EU Treaties can only be amended using the procedure in art. 48 TEU.
- International law: there are no constitutional concerns, the treaty that is concluded later always prevails.
- Jus cogens: its respect is a general limitation for the amendment of any treaty, including EU Treaties.
- Principle of non-regression: amendment of EU Treaties can't lower the protection of fundamental values.
- Respect of EU law: when MS are amending the Treaties they still are MS, and are not above EU law, which makes it an autonomous legal order.
- States as the "masters of the treaties": if all MS decide on an amendment, legal recourse (Commission and Court of Justice use the infringement procedure against all MS) may be useless.
- EU law is based on international instruments, MS are still capable of forcing their political will against EU institutions.

*** Pringle case

- Pringle: is a member of the Irish parliament, argued that the simplified amendment procedure shouldn't have been used, and that the ESM Treaty violated the Union's competence concerning the Economic and Monetary Union.
- Simplified procedure: the formal changes were inside the scope of the simplified amendment procedure, but the Court had to verify whether the substantive changes were as well.
- ESM's purpose: safeguards the stability of the Euro area (not the stability of prices), and is a financial measure (not a monetary one), so it falls outside the EU's exclusive competences.
- Purpose of amending the Treaty: it clarified a pre-existing competence of the MS, who are free to collaborate in economic policies (where the EU has coordinating competence), as long as they comply with EU law (595).
- Dual nature of the ESM: it's a Treaty concluded by MS among themselves, but allocates some tasks to the EU institutions, the Court stated that the allocation is possible as long as it's not done in an area of exclusive competence, or alters the institutions' essential character (596).
- The Court supported the emergency mechanism because opposing it would've worsened the economic crisis (597).
- Political reason for codification: codify the principles for financial assistance, in particular strict conditionality.
- Legal reason for codification: make sure that the ESM integrates with EU law and institutions without issues.

*** Conference on the future of Europe

- Union competences: crises have led to changes in the Union's competences, legal workarounds had to be created around the existing system of competences, a reform may be necessary.
- Decision-making procedures: the number of MS necessitates efficient decision-making, but it must be balanced by measures to ensure legitimacy and accountability, and deal with the issue of MS abusing their voting powers due to democratic backsliding.
- External relations: there is popular support for stronger EU action in the international stage, and to protect Union interests against external interference.
- Reform of the Treaties: is unlikely due to the political circumstances (rise of populism), and constitutional courts are opposed to further integration.

** 2022-11-23

*** Judicial protection of human rights

- European Communities: were created as an international organization with purely economic purposes, there was no need for rules concerning human rights, especially since MS were parties to the ECHR.
- EUCJ: starts recognizing the principles of direct effect and primacy, MS are concerned that EU law could violate constitutional values, including human rights.
- German and Italian constitutional courts: asserted their right to review EU law in order to ensure its consistency with constitutional law.
- EUCJ: reacts to the decision of the constitutional courts by affirming the principle of respect for human rights.
- Stauder case: fundamental rights are a part of the general principles of Community law, and are protected by the Court.
- Internationale Handelsgesellschaft: the protection of fundamental rights is inspired by constitutional traditions common to the MS.
- Nold: international treaties for the protection of human rights which MS are parties to can supply guidelines for Community law.
- Johnston: the principles of the ECHR must be taken into consideration in Community law.
- Kadi: respect for human rights is a condition for the lawfulness of Community acts, and international agreements can't prejudice the constitutional principles of the EC Treaty.
- Art. 6 TEU: mentions the Charter, accession to the ECHR, and "constitutional traditions common to the MS".
- Protection of human rights can't increase the competences of the EU.

*** Accession to the ECHR

- All MS have joined the ECHR, and there were various proposals for the European Community to join the ECHR.
- EUCJ: found that the treaties didn't provide any competence for the European Community to enact rules on human rights, and so it couldn't join the ECHR either.
- Lisbon Treaty: mandated accession to the ECHR, a new draft agreement for accession was made.
- EUCJ: found the draft agreement incompatible with EU law, since accession to the EUCJ would mean that EU acts could be reviewed by an institution outside of the EU.
- EUCJ is relying more on the Charter and less on the ECHR, to establish the independence of the EU legal order.

*** European Charter of Fundamental Rights

- External scrutiny: accession to the ECHR, first proposed and then mandated by the Lisbon Treaty.
- Internal scrutiny: creation of a Community "bill of rights" for the EUCJ to ensure compliance of legislation and policies with fundamental rights.
- Charter: was initially proclaimed in 2000, but only came into direct effect in 2009 with the Lisbon Treaty.
- Application: to EU institutions, bodies, and MS when they implement EU law.

*** International agreements and the EU

- International agreements: the EU can conclude them with third countries and international organizations.
- They're a sui generis source of law, but they can have direct effect, and secondary legislation must comply with them.
- EU can conclude agreements in order to achieve Treaty objectives, or to comply with a legally binding Union act, and the agreements are binding on the institutions and MS.

*** Agreements concluded by the EU

- Exclusive competence in international agreements: only the EU negotiates and concludes the agreement.
- Shared competence in international agreements: both the EU and MS conclude the so-called "mixed" agreement, MS must give their consent, an internal EU act may be used to define the obligations between the EU and MS.

*** Agreements concluded by MS

- Agreements concluded by individual MS with third countries before the accession to the EU can still be enforced even if they're inconsistent with EU law, to prevent a breach of the international commitment.
- Agreements concluded after the accession must not be concluded, or amended and replaced, if they're inconsistent with EU law.
- Agreements concluded by all the MS with third countries: must be taken into consideration by the EU institutions when interpreting and implementing EU law, due to the principle of sincere cooperation.
- MS acting as trustees: if agreements can be concluded only by States, the EU can name a MS to act on its behalf.
- Agreements between MS: if they're inconsistent with EU law, they're invalid since EU law prevails, they can be used to support, strengthen or implement EU law (ESM, Schengen Agreement, Dublin Convention).

** 2022-11-24

*** Structure of EU acts

- Heading: specifies the institution that adopted the act, its date, number and title, and relationship with other acts.
- Recitals: contain the motivation of the act, the affected policy areas, intended goals, respect of the principles of subsidiarity and proportionality.
- Legal basis: justifies the adoption of the act, usually is a single article dealing with the most important policy area (111).
- Publicity: EU law is published in the Official Journal of the EU, publication, entry into force and application are distinct.
- Application: the whole act can be delayed to allow the recipients to comply with the obligations, individual provisions can be applied before applying the whole act.

*** Binding acts

- Binding acts: are regulations, directives and decisions, they can contain obligations.
- Legislative acts: are acts adopted using the legislative procedure, they're always binding, but not all binding acts are adopted using the legislative procedure.
- Choice of form: mandated by Treaties in some areas, otherwise the institutions are free to choose, but should use the least intrusive form (104).

*** Regulations

- Characteristics: binding in their entirety, directly applicable in all MS, analogous to a national law.
- Direct effect: they don't have to be transposed into law, but can mandate national provisions for their implementation (104).

*** Decisions

- Characteristics: binding in their entirety, but only to their addressees, have direct effect (105, 106).

** 2022-11-28

*** Directives

- Characteristics: impose an obligation of results, only MS can be their recipients.
- Framework law: follows the principle of subsidiarity, the EU only defines the policy objectives, States amend their national law accordingly (104).
- Entry into force: 20 days after their publication, beginning of the obligation to transpose the directive into national law.
- Deadline for implementation: after it expires, the Commission can start infringement proceedings if the State hasn't implemented the directive yet.
- Unimplemented directives: unconditional and sufficiently precise provisions can have direct effect to safeguard the useful effect of the directive (cf. Van Duyn case), the Court can impose financial penalties (105).

*** Directives: case law

- Marleasing SA: directives can be used for consistent interpretation purposes, as long as they don't contrast with the literal meaning of national law.
- Frankovich: States are liable for damages if a directive recognizes rights to individuals, and isn't implemented in time.

** 2022-11-30

*** Recommendations and opinions

- Characteristic: they have no binding force in themselves, but non-compliance may cause the adoption of binding acts (107).
- Soft law instruments: are used in areas of regulation that are too sensitive for traditional command and control mechanisms.
- Judicial review: applies to any instrument that creates legal obligations, regardless of the name (108).
- Opinions: have to be requested, they represent the institution's opinion on an issue.
- Recommendations: are given to addressees, and define a certain course of action.
- The distinction between opinions and recommendations is not official, and the "reasoned opinion" in infringement procedures has an addressee and a deadline, which makes it more of a "recommendation".
- Grimaldi case: even though recommendations aren't binding, due to the principle of sincere cooperation they should be taken into account when interpreting national law.
- Binding "opinions": by the Parliament in the legislative procedure, by the EUCJ on draft agreements that the EU wants to conclude with third countries.

*** Primacy of EU law

- Costa v. ENEL: the Court held that Community law can't be overridden by national law, due to its special and original nature.
- Principle of primacy: it isn't found in the treaties, and was developed by the EUCJ.
- Relationship with direct effect: they're strongly connected, but don't necessarily follow from each other, and together they ensure the respect of EU law (175).
- Primacy and validity: primacy does not affect the validity of national law, it only requires that the conflicting provision is not applied in the specific case (but courts may reach different conclusions).
- Dualistic approach: there are two separate legal orders, the institutions in one legal order can't affect the norms in the other.
- Primacy includes all sources of EU law, which prevails over subsequent national legislation.
- National judges and administrative authorities don't have to ask the EUCJ whether they can set aside national laws, and can do so at any point, and irrespective of prohibitions in national laws (176, 177).

*** (cont.) Reaction by MS

- MS have resisted the idea of absolute primacy with various arguments.
- MS as "Masters of the Treaties": the foundation of EU law is the Treaties, not its special and original nature, it's an international law organization, MS aren't bound in an absolute manner (178).
- EU law and Constitutions: EU law is under or beyond national constitutions, but not above.
- Constitutional courts: can review EU acts to determine if the EU has violated the principle of conferral (179).
- Protection of rights from EU institutions is another reason for opposition against absolute EU primacy (180).

*** Principle of consistent interpretation

- Also known as indirect effect, it's analogous to the duty of constitutionally consistent interpretation.
- Applies in general to all EU law and all national law, for all national authorities.
- Weak direct effect: EU law merely confirms an interpretation that was possible under national law.
- Medium direct effect: EU law determines the choice between various interpretations.
- Strong direct effect: EU law imposes a certain interpretation of national law.
- Limitations: consistent interpretation must be balanced with general principles (legal certainty, legitimate expectations, non-retroactivity) and can't be contra legem (contradict national law).

*** Direct effect

- Direct effect: the EU provision becomes the immediate source of law, and doesn't require implementing measures in the national legal order.
- Van Gend en Loos: private parties can invoke provisions from the EEC Treaty, the Court of Justice recognizes that Community law creates obligations and rights for individuals.
- Van Gend en Loos rule: the treaty rule was a clear, unconditional prohibition that didn't require further implementation (no discretion for MS to adapt it).
- Conditions for direct effect vary on the source of law, but in general, only provisions that only contain aim-setting norms, that establish new institutions, or that are subject to considerable discretion by MS are excluded.

*** Direct effect: sources of law

- Treaties: the key Treaty provisions (freedoms, competition law, State aid, equal pay) have direct effect in all types of legal relationship.
- Charter: they can have direct effect in vertical ascending relationships (they limit State power) and sometimes horizontal relationships (discrimination, paid leave), but they tend to be too vague for the direct effect doctrine.
- Regulations: they may or may not be directly applicable (i.e., not require implementing measures), direct effect is presumed, and applies to all legal relationships (vertical and horizontal) (163).
- Decisions: addressed decisions have direct effect if they're clear, precise and unconditional, but only in vertical relationships.

*** Direct effect: directives

- Treaties and regulations: enjoy full direct effect.
- Decisions and directives: the type of legal relationship matters (164).
- Van Duyn: directives can be vertically directly effective (citizens can use a directive against the State).
- Estoppel doctrine: directives can't be directly effective in reverse vertical relationships (a State must implement a directive in order to enforce it).
- Marshall: directives can't be directly effective in horizontal relationships because they only impose obligations on MS.
- However, there is a number of exceptions that increase the scope of direct effect for directives.
- Scope of vertical relationships: relationships with any organization or body under the control of the State, and the State itself acting in private capacity are always considered vertical, and not horizontal.
- Mangold: if a directive contains a general principle of law, the principle is applicable horizontally.
- Indirect effect: also known as consistent interpretation, the same result that would be achieved by the direct effect of a directive in a horizontal relationship can be achieved by consistent interpretation.

** 2022-12-01

*** Judicial control

- Jurisdictional control: is strictly related to the rule of law, which can be enforced both at the supranational (EU) and national (MS) level, based on the principle of sincere cooperation (cf. preliminary ruling mechanism).
- EU judicial institutions: Court of Justice, and General Court (court of first instance) (283, 284).
- Advocate generals: deliver impartial opinions on points of law, which aren't legally binding.
- Private applicants: direct access to the Court of Justice is subject to stringent requirements, it's possible to challenge EU acts before a national judge who can then use the preliminary reference mechanism.
- Jurisdiction: the Court has full jurisdictions in most EU matters, except for Common Foreign and Security Policy matters, and acts of the European Council and Council determining that a MS has committed a serious and persistent breach of fundamental values.

*** Action for damages

- Aim: obtain award in damages, not a declaratory action.
- Standing: any party, including natural and legal persons, with no limitations on standing.
- Time limit: 5 years from the event giving rise to liability.
- Despite the generous conditions, it's rarely successful due to the strict interpretation of the conditions.
- Conditions: unlawful act by an institution, actual damage suffered by the applicant, causal link between the act and the damage.
- Unlawful act: if the institution has discretion the breach needs to be manifest and grave, if the institution has no discretion the mere infringement of EU law is enough for liability.

*** Infringement procedure

- Purpose: restore the rule of law, not compensate the victims (but can be used together with the action for damages), or punish the MS (but it's possible to impose sanctions).
- Applicants: usually the Commission (which is neutral), MS can be applicants but rarely are for political reasons.
- Frankovich doctrine: private parties can sue MS in damages before national courts (289).
- Commission: can start proceedings if if considers that a "Member State" has failed to "fulfill a Treaty obligation".
- "State": includes any public body or private entity controlled by the State.
- "Failure to fulfill a Treaty obligation": includes actions, omissions, and obligations imposed by secondary legislation, international agreements, and general principles of law.

*** Infringement procedure: phases

- The Commission enjoys full discretion in whether and when it should start proceedings, it can rank infringements and choose not to pursue some of them (291), these choices can't be challenged.
- Administrative stage: the Commission sends a letter of formal notice, defines the subject matter so that the State can respond with observations, responds back with a detailed opinion (which may enlarge the scope of the subject matter), and the State has to comply with the opinion by a certain deadline.
- Judicial stage: is triggered if the State doesn't comply with the opinion, the Court will declare whether the State has breached EU law, and can adopt interim measures.
- The Court only cares about the objective breach of EU law, State defenses are generally unsuccessful (292).

*** Infringement proceedings: sanctions

- Failure to comply with the Court's judgment results in the imposition of a penalty (292), calculated on the basis of the population and economic relevance of the State in the EU, and duration of severity of the breach.
- Sanctions are executed by withholding money that would've been granted to the MS.

** 2022-12-05

*** Annulment action

- Time limit: two months from the publication or knowledge of the act, to limit uncertainty (294).
- Reviewable acts: must be "legally binding", includes legislative and non-legislative acts, excludes recommendations and opinions.
- Non-formalistic approach: form or title are irrelevant, only the production of legal effect is relevant, each act must be interpreted individually.
- Acts must come from EU institutions, MS can't be defendants (295).

*** Annulment action: standing

- Privileged applicants: the Member States, Parliament, Commission and Council can bring proceedings unconditionally (296).
- Semi-privileged applicants: Court of Auditors, ECB and Committee of the Regions can only bring proceedings if their prerogatives are at stake.
- Non-privileged applicants: include natural and legal persons, there are strong limits to their participation to avoid overloading the court of justice (297).
- Non-privileged applicants who are addressees have automatic standing, non-addressees need to meet the general standing test, or the Lisbon standing test (297).

*** Annulment action: general standing test

- Non-addressees can challenge acts of "direct and individual concern".
- Individual concern: the attributes or circumstances of a certain person differentiate them from everyone else, as if they were directly addressed (298).
- If the person is part of an "open category" of people, and others could join this category at any time, they are not individually concerned (299).
- The test is restrictive, and individuals who don't meet it can try to bring proceedings before a national court, and ask for a preliminary reference (302).
- However, it's not always possible to start proceedings, and it's not guaranteed that the judge will ask for a preliminary ruling, leading to situations of denial of justice (304).
- Direct concern: there is a direct casual relationship between the act and the effect on the applicant, and the applicant has no discretion in adopting or implementing it.

*** Annulment action: Lisbon test

- Lisbon Treaty: introduced the possibility for non-addressees to bring an action against "regulatory acts" that are of direct concern and that don't require implementing measures.
- The Lisbon test doesn't require individual concern, which should improve the ability of non-privileged applicants to challenge EU acts (305).
- Regulatory act: the Court defined them as acts of general application (as opposed to individual acts), and non-legislative (not adopted according to the OLP or SLP).
- Direct concern: there is no discretion on part of the addressee in implementing the act.
- Doesn't require implementing measures: if implementation is required, then one should bring an action against who implemented it, this requirement is interpreted in a formalistic way (absolutely no implementing measures).

*** Annulment action: grounds for annulment

- Lack of competence: the institution lacked the power to adopt an act, and didn't have an appropriate legal basis.
- Infringement of an essential procedural requirement: breach of a rule that could influence  the content of the act.
- Infringement of the Treaties, or rules related to their application: includes the Treaties, international agreements, customary international law, general principles of EU law, rules of secondary EU law.
- Misuse of powers: the act isn't a proper use of the powers assigned to the EU, this has to be proven by the applicant.

*** Annulment action: effects

- Ex tunc: the effect of annulment is from the adoption of the act, and it will be treated as if it had never existed (312).
- Exceptions: the court can preserve some effects of the act to protect the legitimate expectations of the parties.

*** Action for failure to act

- Complement to the action for annulment, it's used when an institution failed to adopt an act when it was required to do so (312).
- Prerequisite: the institution must have been called upon to act (312).
- Time limit: two months after the pre-litigation phase.
- Applicants: are divided in privileged (EU institutions, MS) and non-privileged (private parties).
- Purely declaratory nature: it only results in a declaration that the law has been breached, without the further effects that other remedies would have.

*** Preliminary reference

- Preliminary reference procedure: is non-contentious, and a form of collaboration between national courts and the Court of Justice, it's not based on a hierarchical relationship, but the separation of tasks.
- Purpose: ensure that EU law is applied uniformly (316).
- "Court or tribunal of a Member State": certain factors (established by law, permanent, binding jurisdiction, independent, procedure must be inter partes, court must apply the rule of law, must be independent) (317, 318).
- Courts performing administrative functions can't ask for a reference.
- Administrative bodies that perform a judicial function can ask for a reference.
- Arbitration bodies can request references if they're permanent and they have obligatory jurisdiction by law.
- Other requirements: the court and tribunals can only refer a question if there's a pending case, and the proceedings will result in a judicial decision (318).

*** Preliminary references: on interpretation and on validity

- Interpretation: can concern both binding and non-binding acts, including the interpretation of general principles, and international treaties.
- The Court can't declare national law invalid (outside of infringement proceedings), but national judges can ask for an interpretation to determine whether national legislation is against EU law (318).
- Validity: can only concern binding acts, only the Court can declare a EU act invalid, national judges can always confirm the validity of EU acts (and not make a reference) (319).
- Preliminary references on validity are an alternative for annulment proceedings, but there are limits (the measures may not require national implementing acts, the applicant would have to break the law, national law makes it difficult or impossible to challenge national measures implementing EU law).
- The Court thinks it's the national courts' duty to ensure effective judicial protection in fields covered by EU law.

*** Preliminary references: discretion to refer

- National courts "may" make a reference, and the Court of Justice can't interfere in this discretion (321).
- Limitations: there is no real dispute (the proceedings were started only to trigger a reference on a certain point of EU law), the referred question is irrelevant to the case, or hypothetical, or unclear or unsubstantiated (322).
- Obligation to refer: if there would be no remedy against a court (supreme courts, small courts with no appeal).
- Exceptions: Court already answered the question in a previous case, or the provisions are sufficiently clear and there's no reasonable doubt (which jeopardizes the uniform application of EU law).
- Illegal EU acts: national Courts still need to refer if they think the EU act is illegal and don't want to apply it, because only the Court of Justice can determine the legality of an act.
- Liability: if the Court violates its duty to submit a reference, the individual can claim damages from the State for its violation of EU law.
- Parties only have an advisory role, only the Court decides whether to refer the question.

*** Preliminary references: effects

- Interpretation: binding on the referring court and other courts deciding the same case in the same proceedings, authoritative for other courts and public authorities, but national Courts can always submit a new reference to try and change the Court of Justice's opinion.
- Act is declared invalid: in theory is only binding on the referring court, in practice it achieves the same result as the action for annulment.
- Act is declared valid: has no erga omnes effect, since other arguments could be used to question the validity of the act.
