* 2021-11-19

** 20:34

- Il divieto di atti emulativi risale al periodo della scienza giuridica pre-accursiano.
- La scuola dei glossatori nasce con Irnerio nel primo decennio del 1100, e raggiunge la sua maturità (e contemporaneamente entra in crisi, richiedendo una riforma dei metodi) con la Glossa Ordinaria di Accursio, negli anni '30 del 1200, che costituisce la sintesi dei dibattiti sviluppati dai professori precedenti.
- Le lezioni erano solo orali, e le tracce scritte delle spiegazioni erano gli appunti degli studenti.

** 23:00

- Il primo filone di scienza giuridica è quello delle opere di sintesi, prodotte dai grandi dottori di leggi vissuti prima di Accursio.
- Ad es., la /Summa codicis/ di Piacentino (riassunto del Codice di Giustiniano, Piacentino muore verso la fine degli anni '90 del 1100), la /Summa in tres libris/ di Pillio da Medicina (dei primi decenni del 1200), e la /Summa codicis/ di Azzone, che sarà il maestro di Accursio a Bologna.
- Esiste una buona sensibilità nei confronti della necessità per il proprietario del fondo rustico o urbano di usarlo in modo equo.
- In alcuni casi, specie per gli edifici nelle città, l'equità viene definita espressamente come una condotta priva di emulazione, riprendendo il termine da un frammento di Macro.
- Il frammento richiedevano che le opere che venivano erette in città necessitassero di un'autorizzazione, se c'era il sospetto che fossero costruite per rivaleggiare con una città vicina, se fomentassero sedizioni o rivolte, o se si trovassero in luoghi critici (circhi, teatri e anfiteatri).
- L'uso del termine /emulazione/ riguarda esclusivamente le situazioni di rivalità fra proprietari di edifici in muratura su fondi urbani.
- Nell'ambito dei fondi rustici, non si trova il sostantivo /aemulatio/, ma formule che comunque ne riproducono il contenuto.
- Ad es., lo scavo fatto per giovare a sé stessi ed il proprio fondo è lecito anche se reca danno al vicino, ma lo scavo nel quale non si trovano questi estremi e causa danni è illecito, e dà al vicino il diritto di ottenere un risarcimento.
- Ad es., lo storno delle acque ha grande rilievo per i conflitti fra proprietari di fondi rustici confinanti, perché l'acqua è un /bene omnium communis/ per il diritto romano, e può essere goduta ed usata, ma va restituita ai fondi che si trovano lungo il corso, con lo stesso volume e forza.
- La trattazione dei giuristi medioevali è aiutata dal fatto che nel Digesto si trova un'azione tipica, /Actio de aquae pluviae arcendae/.
- Tutela le condotte di chi stornano il corso d'acqua per evitare che il proprio terreno si allaghi, oppure per irrigare il proprio terreno.

** 30:12 Azzone: raccolte di brocardi

- L'ultimo passo del glossatore Azzone è anche il più maturo, e non è tratto dalla /Summa codicis/, ma dalla raccolta di /regulae iuris/ chiamata /Brocardica aurea/.
- Le raccolte di brocardi sono un ausilio per l'insegnamento agli studenti, e la prima raccolta è di Azzone.
- Il metodo che Azzone utilizza è di porre a confronto due regole tratte dall'opera di Giustiniano, che sembrano fra loro contraddittorie, per poi dimostrare che in realtà non lo sono.
- Usa il metodo della /distinctio/, di passare dal generale al particolare.

** 33:19 Azzone: danni causati dall'immissione

- Azzone mette a confronto due regole, quella per cui nessuno può compiere attività che danneggino gli altri, e quella per cui è lecito ad ognuno fare sulla sua proprietà quello che vuole, se non reca danno ad altri.
- Partendo da un'attività oggettivamente lecita, ci sono due alternative.
- Se c'è un'immissione nella proprietà del vicino, è chiaramente vietato dal Digesto.
- Questo principio romanistico è sopravvissuto anche nella codificazione napoleonica, e nel codice civile italiano del 1942, dove l'art. 844 impone la tolleranza per le emissioni, nei limiti della normale sopportabilità.
- Se non c'è alcuna immissione, ma si produce comunque un danno, si deve verificare se l'intenzione del soggetto era di danneggiare il vicino, una situazione che va provata in giudizio.
- Pertanto, se il soggetto sta agendo in maniera lecita per migliorare il suo terreno, e causa fortuitamente un danno, non è possibile invocare l'/actio doli/, dato che non ha agito per danneggiare il vicino.
- Si distingue fra la situazione in cui viene utilizzata una cosa propria, ma il danno è accidentale, oppure è previsto e voluto.

** 47:48 Artificiosa duplicazione degli atti emulativi da parte della scuola dei glossatori

- Gli atti emulativi sono oggetto di una artificiosa duplicazione, da parte della scuola dei glossatori.
- I glossatori compievano un'interpretazione letterale dei libri di Giustiniano, e più in particolare, delle parole che presentavano delle incertezze riguardo il loro significato letterale o tecnico.
- Nella compilazione giustinianea, il sostantivo /aemulatio/ compare solo in due luoghi (il frammento di Macro /opus novum/, e una costituzione imperiale in cui si imponeva ai funzionari delle pubbliche amministrazioni di non entrare in rivalità fra di loro).
- La costituzione imperiale è poco utlizzata dai glossatori, perché gli ultimi 3 libri del Codice erano stati scorporati.
- Nelle scuole bolognesi venivano insegnati i primi 9 libri, mentre gli ultimi 3 riguardavano materie di diritto pubblico e amministrativo.
- In particolare, erano largamente riferiti alle istituzioni dell'impero romano d'oriente, e gli istituti descritti o non avevano riscontro, o non esistevano più.
- Pertanto, il frammento più insegnato è quello di Macro, in cui il sostantivo /aemulatio/, che assumerà un significato diverso da quello atecnico di "gara" o "competizione", è utilizzato nel contesto dell'edilizia urbana.
- I glossatori, per non smentire il testo giustinianeo, utilizzeranno nelle loro costruzioni, il divieto /ad aemulationem/, quando si parla di rivalità tra fondi urbani.
- Viceversa, dato che Giustiniano non usa mai quel termine per riferirsi ai fondi rustici, utilizzano delle formule che riproducono il contenuto del divieto, ma senza usare il sostantivo /aemulatio/.
- Pertanto, sembrano esistere due divieti, che però hanno lo stesso contenuto, uno di agire /ad aemulationem/ che riguarda le proprietà urbane, ed il divieto di agire con il solo fine di nuocere ad altri, che riguarda i fondi rustici.
- Nei secoli, questa distinzione formale viene a perdersi, e si userà il termine /aemulatio/ per entrambe le situazioni, ma al tempo dei glossatori la differenza era netta.

** 55:22 Le /quaestiones/ dei glossatori

- Il secondo filone delle opere dei glossatori restituisce una visione più concreta della conflittualità fra i proprietari di fondi confinanti, casi quotidiani e non solo teorici.
- Il metodo delle /quaestiones ex facto emergentes/ sono casi tratti da liti in cui i professori avevano partecipato come avvocati o consulenti.
- Le /quaestiones de facto/ sono importanti nella didattica bolognese, e sono state create della raccolte scritte, che erano utilizzate dai professori.
- La raccolta più antica risale a Pillio da Medicina, negli anni '10 e '20 del 1200, ed è molto probabilmente stata scritta mentre insegnava a Modena, dato il contenuto dei casi riportati.
- La raccolta nel '400 sarà messa a stampa, e continuerà ad essere utilizzata come strumento di esercizio per gli studenti.
- Già la generazione di giuristi immediatamente successiva ad Irnerio (i quattro dottori) utilizzavano le /quaestiones/ nelle loro scuole.

** 1:00:24

- La prima /quaestio/ risale all'età di Martino e Bulgaro (gli anni '60 del 1100), viene risolta da Martino, e proviene dal manoscritto parigino.
- Il /casus quaestionis/, la situazione da cui si parte, consiste in Tizio che vende un fondo a Sempronio, e fa specificare come condizione.
- Al di là del terreno che aveva venduto si trovava un altro terreno, che rimane di sua proprietà, ed era delimitato da un corso d'acqua rispetto al fondo appena ceduto.
- Tizio chiede che Sempronio abbia l'obbligo di costruire un ponte, affinché Tizio possa accedere all'altro fondo che era rimasto di sua proprietà.
- Sempronio costruisce il ponte, che viene successivamente distrutto dall'esondazione del fiume, a seguito di pioggie torrenziali.
- La regola generale secondo il diritto giustinianeo prevede che se la costruzione del ponte è avvenuta a regola d'arte, ed era in grado di resistere ai normali fenomeni meterologici, Sempronio non ha l'obbligo di ricostruirlo, dato che la perdita del ponte era un evento imprevedibile.
- Martino crede che questa soluzione sia ingiusta, e bisogna controllare se, essendo Tizio tagliato fuori dalla sua proprietà, Sempronio non se ne avvantaggi, e la tenga per sé, traendo vantaggio da una sfortuna altrui.

** 1:08:00 (Inizio pausa)

** 1:17:30 (Fine pausa)

- La conclusione di Martino è una conclusione che denota una sensibilità nei confronti di una situazione che lui ritiene ingiusta.
- Non è giusto che Sempronio si appropri di fatto del terreno di Tizio, e gli impedisca l'accesso, per il solo fatto che non è tenuto a ricostruire il ponte.
- Per Martino, il soggetto è comunque tenuto a ricostruirlo, in base all'equità, perché la regola vuole che nessuno si arricchisca a danno di altri.
- In questo caso, non c'è stato il dispetto o rivalità alla base del danno, ma un caso fortuito.
- Questa regola non è una regola giustinianea, ma è una regola di diritto canonico, un principio di morale cristiana, che si può ritrovare anche nelle raccolte canonistiche.
- "Nessuno si deve arricchire con danno o attraverso una disgrazia altrui", non è un principio giuridico, ma è un principio morale.

** 1:21:05 Controversie relative alle acque pubbliche

- Uno dei filoni più ricchi di questioni di fatto per dimostrare la creatività della scienza giuridica dei glossatori per configurare sulla base del diritto giustinianeo norme che il diritto non conteneva, ma che pareva giusto tutelare.
- Il filone più ricco è quello delle controversie relative ai corsi d'acqua, ed in particolare alle derivazioni o uso privato delle acque pubbliche.
- Secondo il diritto romano, i corsi d'acqua pubblici dovevano essere perenni o navigabili.
- Generalmente, i due requisiti tendevano a coincidere (i fiumi perenni sono tali perché hanno una grande quantità d'acqua, e pertanto tendevano ad essere anche navigabili).
- I fiumi pubblici non erano suscettibili di appropriazione privata, ma i privati potevano utilizzare l'acqua che scorreva presso il proprio fondo.
- Tuttavia, devono restituirla con la stessa forza e lo stesso volume, perché sono solo i proprietari del letto del fiume, non anche dell'acqua.
- L'acqua è usata per irrigare le culture, e nell'età medioevale, viene usata per alimentare i mulini ad acqua, che diventeranno l'economia agricola ed industriale, specie nelle zone dotate di fiumi, e non di vento.
- Intorno alla fine dell'undicesimo secolo, ed inizio del successivo, si iniziano a costruire mulini anche nelle città che hanno nella loro prossimità corsi d'acqua pubblici o perenni.
- L'attività tipica è quella di filato (di cotone, della lana, della seta).
- I fiumi del Reno e della Savena a Bologna erano molto più ricchi d'acqua, ed i canali dentro la città permettevano non solo di filare la seta, ma anche di trasportare il prodotto fuori dalla città.
- I comportamenti dei proprietari dei fondi attraversati da corsi d'acqua, nel periodo in cui i corsi d'acqua non erano usati solo per soddisfare bisogni primari, ma anche per attività commerciali che permettevano di arricchirsi, erano oggetto di grande attenzione.
- Qualsiasi abuso da parte dei proprietari dei fondi nell'utilizzare l'acqua che li attraversava poteva danneggiare i vicini, e quindi venivano instaurate liti davanti ai tribunali.

** 1:31:04 Caso del mulino sul fiume

- Molto spesso, il caso in questione riguardava l'uso improprio delle acque.
- Il caso riguarda un mugnaio, Rolandino, che aveva costruito un mulino su un fiume, e lo aveva usato per 30 anni, indisturbato.
- Un giorno, un altro proprietario, che si trova più a monte rispetto a Rolandino  decide di costruire un secondo mulino.
- Di conseguenza, l'acqua che arriva a Rolandino ha meno spinta, e pertanto Rolandino riesce a produrre meno farina, e guadagna di meno.
- Rolandino cita in giudizio l'altro soggetto, accusandolo di avere agito con /vi aut clam/ (violenza) e con dolo.
- Il soggetto terzo dimostra di avere costruito il mulino sul suo terreno, senza aver immesso nulla sul terreno di Rolandino, e che non ha agito con dolo, non voleva danneggiare Rolandino, ma migliorare il proprio fondo.
- Tuttavia, Rolandino riesce a dimostrare di aver ottenuto un diritto di /via aquae ductus/ sul fiume, perché ha esercitato per 30 anni l'attività di mugniaio in maniera indisturbata, quasi ottenendo un monopolio.
- Per Piacentino, la posizione di Rolandino prevale su quella del terzo.
- Non si tratta di atti emulativi (secondo la definizione moderna) perché non c'è la mancanza di utilità, o l'esclusiva volontà di nuocere dell'altro proprietario.
- Tuttavia, i due requisiti sono richiamati, e c'è la posizione prioritaria di Rolandino, che ha diritto non tanto all'acqua in sé, ma alla quantità e forza motrice dell'acqua.
