* 2021-11-02

** 9:16 Prima vita degli atti emulativi

- Il divieto degli atti emulativi è attualmente scarsamente utilizzato nella pratica.
- Se si agisce contro il proprietario che abusa del proprio diritto, ed invade la sfera giuridica di un terzo, è raro vincere.
- L'istituto ha vissuto "due vite".
- La prima, durante l'epoca del diritto comune, dove era stato creato dai glossatori e commentatori sulla base di alcuni appigli contenuti nei libri giustinianei (Codice e Digesto), che erano stati interpretati in maniera estremamente estensiva.
- L'obiettivo era di costruire una limitazione all'esercizio del diritto di proprietà, ed ancora oggi ha questa /sedes materiae/ nei manuali.
- Il diritto romano non conosceva gli atti emulativi in senso stretto, ma offriva delle disposizioni suggestive, che sono state sviluppate (prima con l'interpretazione letterale dei glossatori, poi con quella dei commentatori, andando a cercare la /ratio/ delle norme giustinianee).
- È un divieto di fatto originale, ma viene agganciato, per dargli maggiore legittimità, al diritto romano.

** 14:54 (inizo pausa)

** 15:33 Seconda vita degli atti emulativi

- La seconda vita degli atti emulativi consiste nel percorso che porta al loro inserimento nel codice civile del 1942.
- Inizia con i dibattiti di fine '800, il progetto elaborato dalla commissione per la riforma del codice, e la formulazione definitiva, che si discosta dalla formulazione originale.

** 19:30 Presunzione dell'emulazione

- La legge presume l'esistenza dell'emulazione nei rapporti fra vicini, una formula che risale al giurista trecentesco Baldo degli Ubaldi.
- Inverte l'onere della prova sul convenuto, che deve provare che il suo comportamento non è stato emulativo, a differenza dell tradizionale onere della prova che ricade sull'attore.

** 22:01 /Status quo/: art. 832 c.c. e /uti e frui/ romanistico

- Il terzo libro del codice civile si apre con una serie di principi generali, che valgono per tutti gli articoli riguardanti il diritto di proprietà.
- L'art. 832 c.c. definisce il contenuto del diritto di proprietà, prendendo come punto di riferimento non già la proprietà in sé, ma il proprietario.
- Il proprietario può disporre della cosa in modo esclusivo, pieno ed assoluto, fatti salvi i limiti imposti dalla legge e dai regolamenti.
- Il proprietario ha il diritto di godere e di disporre della cosa, fatti salvi i limiti imposti dalla legge o dai regolamenti.
- Riprende la formula romanistica /uti et frui/ (usare e godere), e nel diritto romano giustinianeo si negava la possibilità di abusare del diritto di proprietà, perché l'/uti et frui/ era pieno ed illimitato.

** 26:14 Possibilità di limitare il diritto di proprietà

- L'art. 832 ribadisce l'illimitatezza, ma prevede anche che si possa limitare la proprietà con leggi e regolamenti, per soddisfare esigenze pubbliche.
- Gli articoli successivi prevedono una serie di limiti tipici che lo Stato può imporrre sulla proprietà.
- L'art. 833 c.c. sono gli atti di emulazione.
- L'art. 834 c.c. prevede l'espropriazione per pubblica utilità, il passaggio forzoso del titolo di proprietà dal singolo allo Stato per esigenze di pubblica utilità, e va compensato con un giusto indenizzo, fissato da legge.
- L'art. 835 c.c. disciplina la requisizione, in cui non c'è il passaggio del titolo, ma una temporanea sottrazione di disponibilità del bene dal proprietario, che è conferita allo Stato, va compensata con indennizzo, e deve essere regolata da una legge.
- Altri articoli limitano i beni dichiarati di valore artistico e culturale per la nazione, che sono comunque espropriabili.
- L'art. 836 c.c. riguarda gli ammassi, l'accumulo di beni primari (la norma era stata scritta nel contesto delle guerre mondiali) da soggetti per uso personale o fini di speculazione.

** 34:00 Divieto di atti di emulazione (art. 833)

- Il titolo con cui si apre il libro sulla proprietà definisce il diritto di proprietà, e poi elenca una serie di limitazioni alla sua pienezza ed assolutezza.
- Tutte le limitazioni riguardano un'utilità pubblica, o un interesse, mentre l'art. 833 è l'unico che riguarda i rapporti fra singoli privati.
- La rubrica dell'art. 833 recita "atti di emulazione", e vieta al proprietario di compiere atti che non hanno altro scopo, se non nuocere o recare molestia ad altri.
- Gli atti emulativi nel passato sono stati anche definiti come "atti egoisti" o "atti dispettosi"
- Per essere giuridicamente una limitazione al diritto di proprietà, devono presentare due elementi.
- La mancanza di una oggettiva utilità, che può essere anche minima, che il proprietario deriva dal compiere quell'atto, e il movente esclusivo di danneggiare il terzo, l'/animus nocendi/.

** 40:24 Dibattito nei lavori preparatori per l'art. 833 c.c.

- La dottrina civilistica era divisa in un dibattito sulla formulazione degli atti emulativi, perché rappresentava una innovazione rispetto ai precedenti codici civili.
- Né quello del 1865, né i codici preunitari, né il codice civile napoleonico contenevano il divieto di atti di emulazionem onostante la sua lunga tradizione.
- La ragione per cui il codice civile napoleonico non riprende il divieto di atti emulativi sia perché il codice civile celebra la proprietà.
- Gli dedica il secondo e terzo libro, a riprova del fatto che la proprietà è il diritto soggettivo principe riconosciuto al cittadino, nella sua pienezza ed assolutezza.

** 44:40 /Liberty e property/ nel codice civile

- L'ideale di /liberty and property/ della tradizione inglese viene riproposto nel codice francese, si abbandona la proprietà latifondiaria dell'aristocrazia feudale e si passa alla piccola e grande proprietà borghese.
- Il proprietario il cittadino-tipo a cui si rivolge il codice, che è pensato per una società borghese, di mercanti, commercianti, artigiani, e successivamente industriali, ai quali il codice deve garantire il massimo rispetto della proprietà.
- La proprietà non è solo un diritto "esclusivo", ma anche "escludente", perché nella tradizione politica di /common law/, e poi in Francia ed Italia, il diritto al voto era legato al censo, e quindi permetteva di rappresentare solo i proprietari.

** 48:19 Inizio della crisi del codice del 1865

- Il codice del 1865 è un codice borghese e conservatore, espressione della destra storica, e non riconosceva la tradizione degli atti emulativi.
- Questa scelta sarà messa in discussione negli anni '80 dell'800, quando il contesto economico italiano (anche se più lentamente del resto d'Europa) inizierà a cambiare, da un'economia pienamente rurale, ad una proto-industriale.
- Questi cambiamenti dimostrano le carenze del codice del 1865, e come alcuni ambiti del diritto non fossero regolati in maniera soddisfacente, o non trovassero alcuna disciplina.

** 52:25 Disciplina del lavoro

- Ad es., nella disciplina del lavoro, il contratto di lavoro disciplinato dal codice civile del 1865 prevedeva due forme.
- La locazione d'opera era usata per il lavoro autonomo, e per il lavoro dipendente si riconosceva solo il bracciantato (in una dimensione rurale).
- Non disciplinava la relazione di dipendenza all'interno delle industrie, un contesto in cui non si poteva estendere per analogia il contratto agricolo.

** 54:30 Necessaria socialità nel codice

- La dottrina tardo-ottocentesca italiana critica la mancanza della necessaria socialità nell'esercizio del diritto di proprietà.
- Il proprietario non può essere considerato come un soggetto a sé stante, a cui tutto è concesso, ma fa parte di una collettività.
- Esistono logiche di solidarietà che dovevano essere recuperate nel codice, secondo parte della dottrina (un'altra parte era contraria), e che non potevano essere violate dal diritto di proprietà.

** 56:25 Immissioni (art. 844)

- Il codice del 1942 conteneva già alcuni elementi, come l'art. 844, rubricato "immissioni", che si trova nel capo dedicato ai principi generali della proprietà fondiaria.
- Il codice impone al proprietario in determinate circostanze di tollerarare le immissioni indicate, all'interno del proprio fondo, a determinate condizioni.
- Il proprietario di un fondo non può impedire le immissioni di fumo o calore, esalazioni, rumori, scuotimenti, ecc., se non superano la normale tolleranza, avuto anche riguardo alla condizione del luogo.
- È un articolo nuovo, perché non era presente nel codice del 1865, né nel codice napoleonico, e non ha nemmeno origini romanistiche, che invece vieta categoricamente l'immissione di fumi ed acqua, in qualsiasi direzione, fra proprietà diverse.

** 1:01:00 (inizio pausa)

** 1:12:05 (fine pausa)

** 1:13:34 (cont.)

- È originale, non ha precedenti immediati né storici, è il portato dell'industrializzazione.
- Gli anni '80 dell'800 rappresentano l'inizio dell'industrializzazione in Europa, principalmente in Inghilterra e Germania, ma in misura minore anche in Italia (le industrie principali sono l'estrazione mineraria).
- È necessario imporre di tollerare una serie di immissioni (di calore, fumo, odori, ecc.), che possono derivare dall'esercizio di un'attività del tutto lecita, sul fondo altrui confinante, fino a quando non superino la normale soglia di tollerabilità.
- In altre parole, l'esercizio dell'attività economicamente rilevante di un proprietario, va tollerata nei limiti della ragionevolezza dal proprietario vicino.
- La tutela dell'interesse socio-economico superiore della produzione supera l'assolutezza della proprietà del vicino confinante, è un interesse pubblico.

** 1:18:36 Art. 844: circostanze dei luoghi

- Si deve tenere conto delle circostanze e dei luoghi, nel senso che la soglia di tollerabilità delle immissioni va proporzionata al contesto in cui si trovano le proprietà confinanti, e va valutata in sede giudiziale.
- Ad es., chi vive vicino a zone industriali deve avere una tolleranza maggiore rispetto a chi vive in una zona residenziale, perché è normale che quel contesto sia più rumoroso.

** 1:24:12 Origine ideologica del divieto di atti emulativi

- Queste ragioni sono incompatibili con gli atti emulativi previsti all'art. 833.
- Le tensioni che avevano portato al divieto di atti emulativo erano state tensioni sociali e solidaristiche, non solo di origine socialista (marxista), ma anche fascista (che era un movimento originariamente socialista, e populista).
- Il fascismo tendeva ad enfatizzare il piccolo borghese, operaio, artigiano, che sono attratti dall'idea della funzione sociale della proprietà.
- Il divieto di atti emulativi è riconducibile sia all'ideologia marxista-socialista che a quella fascista-populista.

** 1:29:23 Art. 2 Cost.

- La tendenza è di passare dalla concezione assoluta ed egoista ottocentesca, alla proprietà a cui è riconosciuta una dimensione sociale, che non deve essere tradita dal proprietario.
- La concezione sociale della proprietà viene costituzionalizzata in due articoli.
- Nell'art. 2 Cost., la Repubblica riconosce e garantisce i diritti inviolabili dell'uomo, e richiede l'adempimento degli obblighi di solidarietà politica, economica e sociale.
- Il diritto di proprietà è uno dei diritti inviolabili dell'uomo, e allo stesso tempo, va esercitato in maniera coerente con i doveri di solidarietà.

** 1:34:54 Art. 42 co. 2 Cost.

- L'art. 42 co. 1 determina che la proprietà può essere privata o pubblica, e che lo Stato può intervenire per ragioni superiori di utilità nazionale per limitarla, salvo giusto indennizzo, e solo in questi casi.
- Nell'art. 42 co. 2 Cost. si afferma che la proprietà privata è riconosciuta e garantita dalla legge, che ne determina i modi di acquisto, godimento e limiti, allo scopo di assicurarne la funzione sociale, e renderla accessibile a tutti.

** 1:37:55 Rapporto fra Costituzione e codice

- La Costituzione nasce dopo il codice civile, e quindi indica dei principi costituzionali, che vanno applicati ad un codice civile che era stato scritto in precedenza, e quindi non conteneva questi principi.
- Ad es., l'art. 832 non fa la minima menzione della solidarietà economica, politica e sociale della proprietà, la stagione che aveva prodotto quell'articolo era diversa.
- La giurisprudenza dovrà interpretare il codice civile, in modo da adeguarlo alla Costituzione.

** 1:40:40 Lavori preparatori del codice civile

- I lavori preparatori del codice civile erano stati molto più solidaristici della versione finale del codice.
- La commissione reale per la riforma del codice civile, che si insedia nel 1924, è motivata dalla crisi del codice civile, davanti alla progressiva industrializzazione, e della prima guerra mondiale.
- Dopo la prima guerra mondiale, diventa necessario adottare l'istituto della morte presunta, e la necessità di abrogare l'autorizzazione maritale, che caratterizzava il codice del 1865.
- Moltissimi uomini diventano scomparsi, e non era possibile provare la loro morte, ma il codice conteneva solo l'istituto dell'assenza dopo 3 anni.
- Tuttavia, l'assente rimane titolare dei suoi beni, e non si apre la successione, e quindi la capacità di amministrare il patrimonio da parte della famiglia.
- Inoltre, le mogli necessitavano dell'autorizzazione maritale per poter disporre della propria dote, ma con il marito assente, non potevano chiederla a nessuno, ecc.

** 1:46:12 Riforma del codice civile del 1865

- In una prima stagione si riteneva di poter riformare singoli articoli, ma successivamente si arriva alla decisione di creare un nuovo codice civile, tanti erano gli interventi necessari.
- L'impostazione originale prevedeva quattro libri (famiglia, proprietà, successioni, obbligazioni e contratti), con un codice di commercio separato (che avrebbe disciplinato anche il lavoro).
- Dino Grandi decide di inserire il diritto commerciale nel codice civile, portandolo da 4 a 6 libri.

** 1:51:11

- Il libro secondo, che come il primo viene pubblicato e sottoposto alla valutazione delle grandi corti del regno.
- ...

** 1:55:03

- L'art. 18 contiene la definizione della proprietà fondiaria, e l'impostazione è diversa da quella usata poi nel codice.
- Il soggetto è la "proprietà", e non il "proprietario".
- Si definisce il contenuto della proprietà, l'/uti e frui/, in maniera piena ed esclusiva, come nel codice civile.
- L'aggiunta originale è il rispetto della "funzione sociale" del diritto stesso, dove "sociale" è intesa nel senso di "corporativa", dello Stato.

** 1:59:30

- Art. 25 contiene l'estensione del diritto di proprietà.
- La proprietà si estende sopra e sotto il suolo, e su quanto è costruito, ed il proprietario può fare sopra il suolo qualsiasi costruzione, piantagione, od opera, nei limiti previsti dalla legge, e salvi i diritti spettanti ad altri.
- Il proprietario non può intraprendere opere che danneggino altri e non abbiano un'utilità propria.
- È un limite emulativo, ma è diverso dal limite previsto dall'art. 833 del codice definitivo, perché considera solo l'elemento oggettivo, e non richiede l'/animus nocendi/.
- Secondo il progetto, l'articolo 25 avrebbe dovuto avere un raggio di applicazione molto più ampio, ed è coerente con l'art. 18, che prevede l'esercizio del diritto secondo la sua funzione sociale.
