* 2021-11-12

** 14:32 Riassunto

- Dall'ultimo quarto dell'Ottocento, la dottrina comincia a considerare come la formulazione del codice civile del 1865, che definiva la proprietà come un diritto esclusivo, fatti salvi i limiti imposti dalla legge e regolamenti, non tenesse conto di esigenze legate al contesto sociale, in cui la proprietà era necessariamente calato.
- Il diritto non andrebbe esercitato /ultra modum/, oltre le regole non scritte della solidarietà e socialità, il vivere all'interno della stessa comunità.
- In Italia, gli autori hanno cercato di ricondurre il divieto degli atti emulativi all'uso delle acque.

** 17:18 Trattati sull'uso delle acque

- L'uso dell'acqua è il luogo migliore per la discussione dell'uso e abuso del diritto di proprietà, dato il carattere dell'acqua di /res omnium communis/ secondo il diritto romano, una cosa comune a tutti.
- Il proprietario nel cui fondo scorre un corso d'acqua può utilizzarlo, ma deve resituirlo così come lo ha ricevuto, perché è solo padrone del fondo e del letto del fiume, ma non dell'acqua in sé.
- Il diritto romano distingueva fra i corsi d'acqua pubblici o privati.
- I corsi d'acqua pubblici, secondo la definizione classica, poi ripresa dal diritto romano giustinianeo, sono o perenni (non erano legati alla caduta delle piogge, ed erano sempre ricchi d'acqua), o navigabili.
- Di fatto, i due requisiti tendono a sovrapporsi.
- I corsi d'acqua pubblici sono /res omnium communis/, a differenza dei corsi d'acqua privati, ossia corsi d'acqua stagionali, che si asciugavano durante le stagioni calde, e per cui valeva la piena proprietà privata, ed il proprietario poteva goderne come meglio credeva.
- La trattatistica del XIX secolo si sviluppa intorno ai corsi d'acqua pubblici, che nell'ultimo quarto dell'Ottocento servivano anche per alimentare i macchinari industriali, e come vie di trasporto legate all'industria.

** 22:51 Silenzio ambiguo del codice

- La tesi degli autori che vogliono recuperare un limite di equità al diritto di proprietà opera nell'ambito della materia delle acque, che per la speciale natura del bene, non è generalizzabile.
- Inoltre, il codice civile non dice nulla riguardo ai limiti equitativi del diritto di proprietà, che può essere visto sia come la volontaria assenza di qualsiasi limitazione, sia come la mancanza della necessità di esplicitare una limitazione che era già presente nell'ordinamento.

** 25:02 Carlo Lozzi: introduzione

- L'idea che il divieto sia già presente all'interno dell'ordinamento è stata ripresa da vari autori.
- È l'autore di uno scritto intitolato /Introduzione al codice civile ed al diritto internazionale privato/ (1880).
- È in contrasto con Scialoja, e sostiene che il divieto degli atti emulativi può essere argomentato dal diritto comune, dalle disposizioni del codice civile, e appare manifesto dal principio di equità, previsto dall'art. 3 delle preleggi, e reclamato dalle nuove dottrine dell'economia.
- Scialoja è contrario a qualsiasi interpretazione che restringa il diritto di proprietà, prendendo come riferimento il silenzio del codice civile, perché non si può far dire al codice quello che non dice.

** 28:53 Lozzi: argomenti a favore del divieto di atti emulativi

- Lozzi si pone in una prospettiva diversa, per cui il principio che impone un equilibrio nell'esercizio del diritto di proprietà ha origine nel diritto romano e comune, e fa parte della tradizione storica del diritto civile italiano.
- Inoltre, risponde a quel principio di equità nell'esercizio dei diritti soggettivi, che è riconducibile all'art. 3 del codice civile.
- L'art. 3 è contenuto nel titolo preliminare sulla legge in generale, ed indica all'interprete le fonti del diritto da applicare nella decisione di una controversia.
- Prevede che nel silenzio del codice, operino il principio dell'analogia, della buona fede e dell'equità, e quindi la mancanza di una limitazione equitativa espressa può essere risolta dal principio di equità, in via sussidiaria.
- Lozzi inoltre ritiene che il principio di equità nell'esercizio del diritto di proprietà è richiesto anche dalle regole non scritte dell'economia.
- La crescente industrializzazione richiede che aumenti la soglia di tolleranza dei proprietari, rispetto alle esigenze della produzione e del mondo dell'industria, che possono portare a delle invasioni della proprietà privata.

** 33:29 art. 3 del codice civile del 1865

- L'art. 3 non menziona espressamente il principio di equità, ma usa un termine generale, che Lozzi ritiene comprensivo sia della tradizione storica, che dell'equità,
- I "principi generali del diritto", che ispirano gli articoli del codice anche nei suoi silenzi, devono necessariamente ricomprendere la tradizione storico-giuridica, ed il principio di equità.
- I giuristi sono consapevoli dell'opportunità di interpretare i silenzi del codice civile, perché la società stava cambiando, ed i codici, come qualsiasi legge scritta, dovevano essere interpretate ed aggiornate, ma senza tradire il loro significato letterale.
- Il modo migliore per mantenere il codice al passo con la realtà di fatto è di usare l'ideologia del codice, i suoi principi generali, residuali, le clausole equitative, etc., in cui far rientrare tutte le norme che non sono espressamente previste dal codice.

** 39:23 Vittorio Scialoja

- Questa è la posizione di Scialoja, inizialmente romanista, e poi ha passato all'insegnamento del diritto civile, è stato presidente dal 1924 della commissione reale per la riforma dei codici, è stato anche ministro guardasigilli e rappresentante dell'Italia per le nazioni unite.
- Era un personaggio autorevole ed influente, ed entra nel dibattito relativo all'opportunità di codificare, pur nel silenzio del codice, un divieto di condotte emulative e di limitare il diritto di proprietà.
- Afferma che qualsiasi interpretazione estensiva del codice non potesse violare i silenzi previsti del codice, se non tradendolo.
- Inoltre, richiamarsi all'origine romanistica del divieto di atti emulativi era una mistificazione, il diritto romano classico e giustinianeo non prevedevano quel divieto, che invece era stato elaborato dalla scienza giuridica medioevale e moderna.
- Esistevano alcune disposizioni giustinianee che fornivano appigli, ma non affermavano esplicitamente il divieto emulativo.
- Nemmeno l'argomento storico poteva giustificare quella che per Scialoja era un'interpretazione in piena contraddizione rispetto al codice civile vigente.

** 43:42 Scialoja: esperto della materia degli atti emulativi

- Si poteva parlare di un divieto di condotte emulative solo per la materia delle acque, che però hanno una natura particolare, ed un regime speciale, e quindi non può essere esteso a tutti i beni.
- Scialoja diventa un esperto nella materia degli atti emulativi, e gli viene offerto di scrivere la voce /aemulatio/ nella prima enciclopedia del diritto italiano.

** 48:08 Scialoja: origine medioevale del divieto di atti emulativi

- Il punto debole del ragionamento di Scialoja è la rigidità che oppone ad un'esigenza che non era opportuno ignorare, dato la sua rilevanza sempre maggiore.
- Scialoja riafferma un dogma del modello della proprietà borghese, il divieto assoluto di sindacare le intenzioni intime del proprietario, che riguardavano il motivo e la modalità dell'esercizio del diritto della proprietà.
- Il diritto di proprietà viene visto come naturalmente esclusivo, escludeva i non-proprietari, incluso lo Stato, dall'esercitare qualsiasi sindacato sulla condotta del proprietario.
- Scialoja era un romanista, e critica anche la presunta origine romanistica del divieto di atti emulativi, smentendo le tesi proposte.
- Scialoja aveva ragione, il divieto di atti emulativi non esisteva nel diritto romano classico, ma era stato creato dai giuristi medioevali.
- I giuristi medioevali volevano dare una risposta in termini giuridici a situazioni di fatto che volevano trovare una soluzione alla situazione di fatto.
- L'abuso del diritto di proprietà era frequente, ma poteva essere sanzionato solo moralmente, in un contesto religioso era considerato un peccato, ma serviva una qualificazione giuridica.
- La scienza dei glossatori riuscirà, partendo da pochi passi della compilazione giustinianea, ed interpretandoli in maniera costruttiva, a creare un nuovo istituto del diritto civile, il divieto di agire /ad aemulationem/ del diritto di proprietà.
- Scialoja non percepisce o non vuole percepire l'importanza della scienza giuridica, e la critica solo aspramente.
- Nel diritto romano giustinianeo, che era l'unico diritto romano conosciuto dai giuristi medioevali, l'espressione /aemulatio/ si trova solo in due passi, ed in entrambi i casi non veniva usata nel significato moderno.

** 58:15 Passi che contegnono la parola "aemulatio"

- I due passi sono un frammento del Digesto, ed una Costituzione imperiale.
- Il primo passo è un frammento del Digesto, e si trova nel cinquantesimo libro, al titolo /De operibus publicis/ (D 50.10.3).
- È un frammento di Macro, un giurista dell'epoca classica, esperto della disciplina urbanistica, e di costruzioni all'interno delle città.
- Il frammento è chiamato /opus novum/, dalle prime due parole, e afferma la possibilità per i privati di costruire opere che abbelliscono la città (ad es. tempi, stadi, teatri, etc.), senza bisogno di autorizzazioni dal /princeps/.
- Tuttavia, in tre situazioni è necessario chiedere l'autorizzazione (se l'opera sollecita emulazione da parte di un'altra città, oppure susciti sedizione, intese come rivolte o malcontento all'interno della città, oppure si trovi nelle vicinanze di un circo, teatro o anfiteatro).
- Sono situazioni particolari, che possono turbare la pace cittadina, e creare conflitti fra città diverse, oppure turbative interne alla città stessa, o perché i circhi, teatri ed anfiteatri sono luoghi in cui si riuniscono già grandi folle, e sarebbe inopportuno aggravare ulteriormente la situazione.
- In questo passo, il sostantivo /aemulatio/ va tradotto come "gara, sfida, etc.", e non coincide assolutamente con l'atto emulativo, l'atto fatto con il solo scopo di arrecare danno o molestia ad altri.

** 1:06:31 Secondo passo che contiene la parola /aemulatio/

- Il secondo passo nell'intera compilazione in cui viene usato il sostantivo /aemulatio/ è una costituzione imperiale (C 12.58) intitolata /De Aparitoribus praefectus Annonae/.
- Riguarda la magistratura annona, che aveva il compito di raccogliere la produzione granaria, e metterla a disposizione dei cittadini, per evitare che ne rimanessero senza.
- La costituzione è breve, e statuisce che i funzionari della magistratura dell'annona non devono interferire con l'autorità di altre magistrature.
- Si usa il termine "emulazione segreta", per indicare l'obbligo di lasciare da parte le rivalità, e si afferma un principio di non-interferenza fra le diverse amministrazioni dell'impero.
- Anche in questo caso, il sostantivo /aemulatio/ è tradotto come "rivalità".
- Scialoja aveva ragione quando sosteneva che nella compilazione giustinianea, il termine /aemulatio/ non può essere considerato l'origine del divieto di atti emulativi.

** 1:10:20 Scialoja: /Tusculanae disputationes/

- Scialoja cita un'ulteriore fonte romanistica, questa volta da un'opera di Cicerone, le /Tusculanae disputationes/, una serie di dialoghi.
- Spiega che il termine /aemulatio/ ha due significati, uno positivo ed uno negativo.
- Il significato positivo è riprendere i tratti positivi di qualcuno, l'imitazione /ad meliorandum/, per migliorare sé stessi, ma è l'accezione usata di meno.
- Il significato negativo è più utilizzato e più interessante, dove "emulare" significa "invidiare" la cosa posseduta da altri, al punto da volere la distruzione della cosa, così che anche il terzo non la possa più avere.
- Tuttavia, nessuna delle due definizioni riguardano l'atto emulativo di disposizione del diritto di proprietà.

** 1:14:47 Conclusioni di Scialoja

- Su queste basi, Scialoja afferma che l'origine romanistica è un richiamo improprio da parte dei suoi colleghi, e che la vera origine sia la costruzione operata dalla scienza giuridica medioevale.
- Nel complesso della compilazione di Giustiniano esistono dei frammenti che sono contraddittori, non nella terminologia (il sostantivo /aemulatio/ appare solo due volte), ma nei contenuti.
- Ci sono passi che sostengono un divieto di abuso, e passi che sostengono l'opposto, ma questa era una conseguenza della natura della compilazione giustinianea, che raccoglieva norme anche antiche di secoli, e quindi era possibile trovare soluzioni diverse allo stesso problema.
- Per i giuristi medioevali, la natura della compilazione di Giustiniano era ignota, e pensavano che fosse tutto diritto vigente, e non percepiscono le differenti età temporali.
- Pertanto, si sforzano di eliminare le contraddizioni, pensando che fosse irragionevole che la compilazione potesse contraddirsi, ed è proprio dallo sforzo di interpretazione, che riescono il divieto di atti emulativi, anche se quel divieto espressamente non esisteva.
