* 2021-09-30

** 1:03 The nature of the EU legal order

- The EU may be considered an intl. org., a very peculiar one, since it has developed a proper method of cooperation, the community method
- It is significantly different from traditional cooperation methods, as used by other intl. organizations
- To what extent does this method of cooperation influence the nature of the legal order?
- The nature of the EU legal order can be examined from two perspectives
- The first one is the position taken by the EU institutions, in particular the EU CoJ
- The Court, since the very beginning of the EU integration process, has tried to define the nature of the EU legal order
- There is another version, given by international law and related elements of practice

** 4:08 Van Gend en Loos case

- In 1963, at the very beginning of the integration process, the CoJ decided the Van Gend en Loos case, a cornerstone case in the history of EU
- The factual background isn't important, what is important are the points the CoJ made regarding the nature of the treaties in the European Economic Community
- The first point made by the Court is that the treaty creating the ECC is not an ordinary treaty, it has something more to it
- Ordinary treaties create a scheme where the concerned parties are in mutual position
- E.g., in a bilateral treaty, both parties expect obligations, and the ability to invoke some rights
- According to the Court, the treaty establishing the Community is also able to create legal situations that may be relevant for the individuals, and other subjects of the legal system
- It's not possible to use the classical "mutual" scheme with the ECC agreement

** 8:02 Peculiar traits of the ECC treaty

- This view is confirmed by the preamble to the treaty, which refers not only to "governments" but to "the peoples"
- It is also confirmed by the establishment of institutions with sovereign rights, the exercise of which affects MS, and their citizens
- The nationals of the MS in the Community are called upon to cooperate in the functioning of this community, through the intermediary of the European Parliament, and the Economic and Social Committee
- Art. 177 regulates the so-called "preliminary ruling mechanism", the object of which is to secure the uniform interpretation of the treaty by national courts
- It confirms that the States acknowledge Community law as law that can be invoked by their nationals, before the national courts

** 10:49 Conclusion of the Court

- In light of those elements, the Court asserts that the EU legal order is still an int. law one
- It was established with intl. law instruments (through treaties, agreements, etc...)
- However, it's a very peculiar legal order
- States have transferred upon the community part of their sovereign rights, and individuals may be subject to the legal order
- This position was taken in 1963, at the very beginning

** 13:04 Vienna Convention: art. 5

- Art. 5 of the Vienna Convention on treaties contains a "without prejudice" clause
- The Convention is applicable to international treaties only if the rules don't conflict
- If trey do conflict, then the rules in the treaty must prevail
- It's an application of the "lex specialis" principle, rules in individual treaties must prevail, because they're dealing with specific circumstances
- If art. 5 is applied to the European treaties, one reaches the same conclusion as the Van Gend en Loos decision

** 18:24 Nature of EU law

- EU law prevails due to its speciality, but it's still a form of international law
- The result is the same, regardless of the approach
- The Court of Justice is using an internal point of view, stressing the peculiar elements of the EU legal system
- The Vienna Convention uses an external point of view, and simply states that intl. orgs. may have different rules, and that if they conflict with the V.C., they should prevail

** 19:46 ICJ's advisory opinions

- The ICJ (International Court of Justice, the main jurisdictional body of the UN) can give advisory opinions (a non-binding opinion) on how international law must be applied to a specific issue
- In 1996 the ICJ was requested by the WHO to give an opinion on the legality of the use of nuclear weapons
- At that time, the French Republic had decided to launch a program of nuclear weapons experiments in the Pacific Ocean
- According to the statute of the ICJ, the subjects entitled to ask an opinion are the bodies of the UN, and UN organizations
- In this case, the WHO is an UN organization, but the topic must be covered in the WHO's mandate
- If that isn't the case, the ICJ may decide to reject the request
- E.g., the WHO couldn't inquire about the legality of countermeasures in trades, because that's not part of the WHO's mandate (the WTO is concerned with that)

** 24:10 ICJ's observations about treaties establishing intl. orgs.

- If the ICJ receives a request for an opinion, it must first clarify if the organization is allowed to ask that question
- While the ICJ looked at the statute of the WHO, they made some general considerations on the nature of a treaty establishing an international organization, and the way in which that reaty must be interpreted
- The ICJ decided to look at the constituent instrument of the organization, to properly determine its mandate
- The ICJ makes some observations about treaties establishing intl. orgs., and how how they should be interpreted
- Those treaties have a "dual soul"
- On one hand, they are conventional intl. instruments, so they should be treated as treaty law
- On the other hand, they have an institutional dimension, because they create a new, autonomous entity, with a new legal order
- Therefore, while art. 5 of the Vienna convention applies (since it's a treaty), but some adjustments hav to be made due to the institutional dimension

** 29:29 Art. 31 of the law of treaties 

- Art. 31 states the interpretation criteria that must be used to interpret a treaty
- They are the literal meaning of words, the teleological interpretation (takes into account the scope and objectives of the treaty), and the context of the treaty as a whole (single provisions are not-self contained, but the treaty as a whole has to be taken into consideration)

** 33:14 Implied powers doctrine

- There is an treaty establishing an international organization
- It provides a list of objectives that the organization has to fulfill, and the powers and instruments that can be used to fulfil them
- There is a single case where those powers and instruments aren't specified, only the goal is
- Using a strict literal interpretation (art. 31), then it would be impossible to do anything to achieve that goal, since there are no explicitly mentioned tools to do so
- In order to overcome this obstacle, a specific doctrine that is exclusively applicable to treaties that establish international organizations has been created
- If the drafters of a treaty have given the organization a specific goal, this implies that the powers needed to achieve that goal were also given
- This is a way of interpreting the treaty that isn't in line with art. 31 of the Vienna convention, and takes into consideration of its dual nature
- Art. 352 TFEU codifies the implied powers doctrine, and intl. law can explain the way in which EU law shall be interpreted

** 39:28 ICTY: creation

- The ICTY (International Criminal Tribunal for the former Yugoslavia) was established by the UN SC to prosecute the international crimes committed duringt the Balkan war
- The SC established that tribunal just like the ICTR (ICT for Rwanda) by means of a resolution (cf. art. 39 UN Charter)
- The SC can establish if a specific situation can represent a threat for peace or intl. security, and it can adopt binding decisions which may involve the use of force, or impose obligations
- The ICTY was created within the context of art. 39 UN Charter, the decision was taken because the situation in the Balkans was classified as a violation of peace and intl. security

** 42:42 ICTY: "constitutional limitations"

- The tribunal was established, and in one of the first cases before the tribunal, the argument was made that the tribunal was established in contrast with the UN charter
- Because of that, the tribunal had to examine whether or not it was lawfully created, as a preliminary question
- The ICTY examined art. 39 of the UN Charter, and determined that while the SC has a pivotal role, and enjoys wide discretion under art. 39, its powers are not unlimited
- The SC is still part of an intl. org., established by a treaty, which serves as a constitutional framework for that organization
- Therefore, the SC is subject to certain "constitutional limitations"
- In other words, every treaty that establishes an intl. org. is also a constitution, not in the sense of a "national constitution", but in the sense that it is creating a new legal order
- Intl. law and the practice related to the law of intl. orgs. is perfectly able to explain how the EU legal order can enjoy a certain degree of autonomy within the intl. law context

** 47:57 AG Maduro

- The AG Maduro, in the 2008 Kadi case, which was related to the implementation of UN sanctions against terrorists at the EU   level, gave an opinion
- AGs give a non-binding opinion before the decision of Court, suggesting a possible solution according to EU law
- Judges may decide not to follow the decision, without having to motivate their decision
- Maduro tries to go back to Van Gend en Loos, and update it, some 45 years later
- The question was still related to the relationship between the international legal order, and the community legal order
- In Van Gend en Loos, the Court affirmed the autonomy of the EU legal order, and held that the treaty is not just "between States", but "between the peoples of Europe"

** 51:56 Maduro's innovation on Van Gend en Loos

- However, Maduro is changing the Van Gend en Loos formula, because in that judgement, the Court didn't say that the community legal system was "autonomous"
- The "autonomy" of the EU legal order is mentioned for the first time only by Maduro, and it means that the EU order is no longer part of intl. law, it is a "municipal legal order"
- "Municipal" usually refers to the laws of individual States, but the EU is not a State, it is a "municipal legal order of transnational dimension", in Maduro's words
- It's an update to Van Gend en Loos
- However, just because the EU legal order is separated from general international law, that doesn't mean that it is indifferent to it, there is a mutual influence

** 55:54

- The emphasis on the autonomy of the legal order is more and more present in the European cultural justice, thanks to Koen Lenaerts
- During his presidency, his judicial policy was to affirm the autonomy of the EU legal order, from international law, and the law of individual MS
- On one hand, international law says that treaties establishing international law can enjoy some autonomy, and can prevail over general intl. law
- On the other, the EUCJ states that while it's true that the EU legal order was created by means of international law, it's now completely autonomous, due to its constitutional features
- Looking at the legal practices of the EU, it's clear that EU law is still related to intl. law, albeit as a very particular kind

** 1:00:05 Examples of treaties outside the EU, that support EU objectives

- This practice is also justified by the historical context the EU is going through, which includes an economic crisis
- E.g., the ESM (European Stability Mechanism) is a form of financial assistance for States in the eurozone
- It has been created by means of an intl. treaty, by the MS of the EU, outside the legal system of the EU, but it supports the EU objective of the stability of the eurozone
- It's an example of MS acting outside of the system, by means of intl. law, in order to support the system
- E.g., regarding the refugee crisis, the so-called "EU-Turkey Statement", or "EU-Turkey agreement" was adopted in 2016
- It was created in order to stop the flow of immigrants from the Balkans, and entering into Greece
- It's a treaty, concluded without respecting the proper EU procedure, in order to support the system

** 1:03:12 States can change treaties without respecting the procedure

- E.g., regarding Brexit, in 2018 the EUCJ, the same court that considered EU law as an autonomous legal system, decided the Wightman case
- MS have a sovereign right to leave the Union, which means it cannot be subject to any limitation or condition, they are completely free to decide
- If the EU order is truly autonomous, then it would be difficult to imagine a situation where States would withdraw
- EU primary law defines a procedure to amend treaties, which States have to follow
- However, if States decide together to change the Union, without respecting those rules, they can do so
- It would be a huge shift in the constitutional framework, but States have the power to change it, whenever they way

** 1:06:26 Argument against the autonomy of the EU legal order

- The EU legal order is still in the hands of States
- It can't be "autonomous", because States have the power to change it and destroy it
- EU is still pertaining to intl. law, it's not completely autonomous, it may become autonomous, but it's not the case
- This position is not shared by all scholars, some believe that today's EU law is fundamentally different, it's autonomous
- However, this perspective fails to explain why MS act outside of the system, using intl. law, which implies that the system is not fully autonomous and self-sufficient

** 1:11:13 Summary

- The autonomy of the EU legal order means that institutions are able to impose obligations on MS without being influenced by them
- On the other hand, if EU law is still related to intl. law, it means that its institutions are governed by States
- The rules of international law don't prevent the EU from having a degree of autonomy
- However, one thing is saying that the EU legal order is partially autonomous in the light of its specificities, another is saying that it's a /tertium genus/
- If it's a legal order with a completely independent life, it's harder for States to exercise their original power as "masters"
- However, in reality States are still relevant, and in turn intl. law still plays a role

** 1:15:32 Legal populism

- There are worldwide trends that stress the need to go back to the sovereignity of States, and reject international cooperation
- To some extent, the argument about EU law being autonomous is a sort of legal populism, because it implies that EU law can exist without international law
