* 2021-10-13

** Comments on the Sweden and EU Commission case

- *00:00:00*.
- The EUCJ's decision breached the principle of proportionality (which was also established by them) because it didn't take into account the context.
- It also breaches the principle of sincere cooperation, since it is functional to fulfilling the EU's interests
- *00:03:00*.
- The decision was taken long before it was published.
- *00:06:00*.
- The decisions are published after they have been translated in all the languages of the EU, which takes time, because the translations have to be accurate.
- One could say the ruling may have been suspended, but it's hard to say that the EUCJ was in breach of the principle of sincere collaboration.
- ... ... ...

** Defining EU's duties towards MS by interpreting art. 4

- *00:09:00*.
- In order to determine the EU's loyalty duties towards MS, one should try to interpret art. 4 par. 3 TEU taking into account the rest of the article.
- Therefore, the principle of sincere cooperation requires that EU institutions must respect the principle of conferral, the equality of States, and national identities.

** Balancing the elements described in art. 4

- *00:12:00*.
- The issue is balancing two elements.
- On one hand, there's a need to preserve the effectiveness of EU law (which implies a degree of flexibility in interpreting the principle of conferral, a limitation of what constitutes a national identity, or the prerogatives of MS).
- On the other hand, those same elements must be taken into account by EU institutions.
- There is no concrete list of obligations on the EU part, it consists on balancing the interests of the MS.
- However, according to the case law of the EUCJ, it doesn't seem to be interested in finding this balance, at least for now.

** Decreasing importance of the principle of loyalty

- The number of cases in which the EU makes a reference to the principle of sincere cooperation is decreasing.
- *00:15:00*.
- In the past, the principle was understood as a sort of "master key", that could be used to define obligations for MS.
- In the last few years, the principle is being used far less, because the EUCJ is worried about the possible reaction of MS.
- They could decide to protest against decisions by stressing the mutual nature of the principle.
- The Court is aware that they're interpreting the principle of loyalty in a unilateral way, and is worried about the possible reaction of States, so they prefer to use other principles that can lead to the same conclusion.
- Instead of developing a new balance in interpreting the loyalty duty, it prefers not to use it at all, and solve the dispute in an alternative way.

** Principle of solidarity

- The last element in the principle of sincere cooperation has to do with the interaction between loyalty and solidarity.
- *00:18:00*.
- The principle of loyalty (or sincere cooperation) is able to incorporate into itself a principle introduced by the Lisbon treaties, the principle of solidarity.
- The origin of the integration process can be traced back to the Schuman declaration, in 1950, which can be considered a sort of political manifesto.
- At one point, it reads that the European integration must be based on a "de-facto solidarity".
- The Community is based on the idea that the States are peers, and that there's a shared brotherhood among themselves, in that they'll assist each other in fulfilling objectives.
- Art. 4 par. 3 makes reference to "mutual assistance", which implies solidarity among peers.
- *00:21:00*.
- However, does "loyalty" automatically imply "solidarity", or does that need to be specified?
- Art. 24 par. 3 mentions both "loyalty" and "solidarity" must be kept together.
- Some provisions in primary EU law reference solidarity, and the concept has been introduced in EU primary law by the Lisbon treaty.
- *00:24:00*.
- Art. 67 TFUE is related to migration, asylum and border controls, and in par. 2 "solidarity" is mentioned as the foundation of the policies in those fields.
- Art. 80 TFUE mentions the principle of solidarity, and fair sharing of responsibilities between MS.
- Art. 122 is a more articulated provision.
- *00:27:00*.
- Par. 1 applies if there are severe difficulties in the supply of certain products, in particular energy products, MS should act in solidarity.
- This provision is linked to art. 194, which deals with the energy policy of the EU, and mentions a "spirit of solidarity" between MS.
- This can sometimes happen in the EU due to decisions taken by non-EU countries who supply MS, especially in Eastern Europe.
- Art. 122 par. 2 TFUE is about States who are threatened by severe difficulties caused by natural disasters, or exceptional circumstances beyond their control, other MS may provide financial assistance in the spirit of solidarity.
- Art. 222 TFUE is the so-called "solidarity clause".
- *00:30:00*.
- According to art. 222, if a MS is a victim of a terrorist attack, natural disaster, or human-made disaster, the EU and other MS are obliged to take all appropriate measures to help the State in need.
- Art. 80 TFEU was used to introduce the relocation schemes involving aslyum-seekers, and derogating the Dublin Regulation.
- *00:33:00*.
- Art. 122 TFEU was used to adopt the SURE Regulation as a response to the pandemic, in order to give financial assistance to the workers in the MS who were affected. 
- Art. 122 TFEU was also used to adopt the ESI (Emergency Support Instrument), which was adopted in 2016, to provide assistance to Greece during the refugee crisis.
- In 2020, the scope of application of the ESI was extended, to also cover the pandemic, the idea was to strengthen the budget of this facility to the States in need because of the pandemic.
- *00:36:00*.
- The decision was taken to use this facility to fund the advance purchase agreement (APA) the EU Commission has concluded with pharmaceutical companies to obtain vaccines.
- The APA is concluded before a vaccine is found, so that when it is found, the EU will enjoy a precedence right on its sale.
- All those agreements were funded using the ESI.

** Art. 222 TFEU: French terrorist attacks

- Art. 222 TFEU hasn't been used in practice so far. There was a chance in November 2015, after the terrorist attacks, the French Republic could've used that article.
- *00:39:00*.
- However, the day after the attacks, when the President gave a speech in front of the national assembly, he chose to qualify those acts as an "act of war", which had legal implications.
- It was no longer possible to invoke art. 222 TFEU, since acts of aggression aren't included.
- On the other hand, it was possible to invoke another clause, art. 42 par. 7 TEU, the defense clause, whereby if a State is a victim of an act of aggression, the other MS have a duty to intervene.

** Art. 222: potential to involve the EUCJ

- The President decided to invoke art. 42(7) TEU instead of art. 222 TFEU, because the latter is subject to the community method, meaning that there's a jurisdictional control by the EUCJ.
- Instead, with art. 42(7) there is no control by the EUCJ.
- *00:42:00*.
- This means that there's no possibility to bring a State before the Court for failing to fulfil art. 42(7) TEU.
- Whereas if a State uses art. 222 TFEU, and isn't satisfied by the reaction of the other States, it could claim that the other States have violated their solidarity duties.
- The EUCJ would have to assess the situation, but art. 222 TFEU doesn't say anything about the content of the solidarity obligations.

** Art. 222: vague wording, lack of precedents

- There are assistance duties, there is a duty to take all appropriate measures, but what does "concretely" mean?
- It's difficult to determine the exact boundaries of the solidarity duties, and that's the reason States are hesitant to use that article.
- *00:45:00*.
- The fact that a State can be brought before the Court makes it even worse, which explains why there's no cases yet making use of that clause.

** What is the difference between solidarity and loyalty?

- Solidarity always implies positive obligations, while loyalty may also require negative obligations.
- *00:48:00*.
- Loyalty duties are always relevant for the functioning of the EU, but solidarity duties are only relevant in emergency situations.
- In emergency situations, there is an additional set of obligations, that stem from the principle of solidarity.
- *00:51:00*.
- Implementing the principle of solidarity means that States share the consequences of an emergency situation.
- There is a relevant problem in the enforcement of the principle of solidarity, while it's possible to enforce the principle of loyalty (or sincere cooperation), and there are several important cases.
- Solidarity is taken into consideration by the EU institutions and MS more seriously if it's based on voluntary mechanisms.
- If it's based on mandatory mechanisms, States are less likely to implement solidarity duties.

** EU Civil Protection Mechanism

- Art. 222 TFEU (the solidarity clause) is applicable in theory in a context of natural or man-made disasters, or terrorist attacks.
- There is another mechanism which can be activated in the case of disasters, the EU Civil Protection Mechanism (EU CPM).
- That mechanism can be used if a State is in need because of a natural disaster.
- *00:54:00*.
- That State may ask other MS to provide assistance, but the requested MS may decide whether or not to give assistance, the only obligation is to give an answer quickly.
- In the overwhelming majority of cases, States do agree to provide assistance, refusal is exceptional.
- The CPM has been used very often, but the solidarity clause has never been applied, even though the latter could be applied in the same situations as the former.

** States prefer to exercise solidarity on a discretional basis

- The difference is that the solidarity clause defines duties, while in the case of the CPM there's no legal obligation, only a moral one.
- States prefer to give assistance when they can exercise a discretional power; if they are obliged, they're more reluctant.
- *00:57:00*.
- That is one possible explanation as to why the enforcement of solidarity duties is not so effective.

** Coronavirus pandemic

- It's a different scenario than the one found in the primary sources of EU law, it's a "symmetric" scenario, because all MS have been affected by the crisis.
- In EU primary law, the assumption is made that only some MS are affected by the crisis; at least for now, there are no mechanisms in treaties to deal with EU-wide crises.
- This is why it was hard to set up a strong reaction to the pandemic.
