#+TITLE: Diritto Amministrativo -- Lezioni marzo 2023
#+AUTHOR: Luca Piras

* 2023-03-01
** Dislocazioni periferiche
- Alcuni ministeri hanno dislocazioni periferiche.
  - Ad es., le prefetture e questure per il ministero degli interni, le sovrintendenze, etc.
- Le prefetture hanno la funzione di *rappresentare il governo*, e *coordinare gli uffici periferici* in modo da garantire l'unitarietà di indirizzo.
** Coordinamento
- Esistono forme di *coordinamento procedimentale* e di *coordinamento organizzativo*.
- Il PCDM è un organo stabile, e dirige e coordina il CDM.
- [...]
** Ragioneria dello Stato
- La ragioneria è unica, esistono ragionerie ministeriali e locali.
** Avvocatura dello Stato
- Serve a difendere le amministrazioni dello Stato in giudizio, incluse le amministrazioni indipendenti.
- Ad es., le multe imposte dalle amministrazioni indipendenti sono quasi sempre oggetto di ricorso, per la loro entità.
** Agenzia del demanio e tesorerie
- L'agenzia del demanio si occupa della gestione dei beni dello Stato.
- I beni non sono di proprietà dei ministeri.
- La tesoreria è unitaria, e serve a garantire l'unitarietà dei flussi di spesa.
** Consiglio di Stato
- In molti casi, prima che il CDM possa deliberare un atto, in alcuni casi deve ottenere un parere preventivo, sempre non vincolante, da parte del Governo.
- Sezioni, quarta sezione per la giustizia [...].
** CNEL
- [...]
* 2023-03-06
** Amministrazioni indipendenti
- Sono sottratte dal controllo politico.
- Non hanno la natura di giudice, non possono invocare la Corte costituzionale.
- Sono titolari di una legittimazione processuale straordinaria, e possono impugnare le decisioni della PA che incidono su materie di loro competenza.
- Garanzie di nomina, revoca limitata [...].
- Durata di nomina lunghe, per superare la durata degli organi di indirizzo politico.
- Incompatibilità con altri incarichi [...].
- Autonomia finanziaria:
  - Non sono finanziate solo con il bilancio pubblico, per evitare "ricatti" da parte della PA.
  - Sono finanziate anche dalle imprese regolate.
- Norme europee prevedono l'istituzione di autorità indipendenti, la competenza a livello centrale (europeo) al raggiungimento di certi limiti [...].
* 2023-03-07
** Regioni a statuto speciale
Gli Statuti speciali precedono la riforma del 2001.  Se prevedono un livello di autonomia minore rispetto alla riforma, sono equiparati, se il livello è maggiore, è mantenuto.
** Regioni a statuto ordinario
La Costituzione *obbliga* l'uso del suffragio universale per l'elezione del *presidente*, e lo *permette* per l'elezione del presidente della giunta [...].

Sono previste alcune forme di incompatibilità, ed il principio *simul stabunt, simul cadent*, per cui:

- Se decade il presidente della Regione, decade anche il consiglio regionale.
- Se più della maggioranza dei componenti del consiglio si dimette, o vota per una mozione di sfiducia contro il presidente, decadono entrambi.

La previsione di *premi di maggioranza* dovrebbe prevenire l'insorgere di conflitti politici.
** Regioni come amministrazioni
Sono state istituite con la Costituzione, tradizionalmente [... non esistevano/esistevano solo come limiti territoriali?] e originariamente erano pensate come amministrazioni semplici.

Gli *assessori* ha una serie di *deleghe* dal presidente della giunta.  **Non sono prestabilite dalla legge*, ma dalle decisioni politiche del presidente.  Un assessore può avere più deleghe.

L'amministrazione regionale è basata su *uffici chiamati "direzioni"* che sono stabiliti dalla legge.  La *direzione generale* non è necessaria, ma se è presente coordina le varie regioni.

Regioni di grandi dimensioni riprendono modello statale [...].

Esistono enti pubblici regionali, ad es. le *ASL*, le agenzie per la valutazione dell'impatto ambientale, etc.

Il *difensore civico* è obbligatorio a livello regionale.  Molti comuni preferiscono delegare la funzione di difensore civico comunale al difensore civico regionale.

[...].
** Poteri del governo
Il *potere di scioglimento* è circondato da garanzie.

Il *potere di sostituzione* è usato:

- Quando il diritto europeo impone obblighi, e le Regioni ed enti locali rimangono inerti.
- Per ragioni di incolumità della salute pubblica.

Il *potere di diffida* [...].

Il *potere di annullamento straordinario* non può essere usato nei confronti delle regioni, perché si pone in contrasto con l'autonomia prevista dalla Costituzione.
