#+TITLE: Diritto Amministrativo -- Lezioni febbraio 2023
#+AUTHOR: Luca Piras

* 2023-02-20
- Introduzione alla seconda parte del corso.
- Organizzazione della PA: risorse che utilizza per svolgere le sue funzioni.
- Persone fisiche: non rilevano per quanto tali all'interno della PA, ma solo in quanto persone che ricoprono un certo ruolo.
- Persone giuridiche: non è necessaria per il diritto pubblico, le "figure soggettive" ...
- La personalità giuridica per il diritto privato riguarda la capacità di essere titolari di diritti, la soggettività amministrativa riguarda ...
** Pluralità delle PA
- Le PA sono una pluralità ("pubbliche amministrazioni").
- La Costituzione menziona una serie di soggetti (comuni, province, città metropolitane, regioni...).
- L'aumento del numero dei compiti dello Stato rende necessaria una maggiore specializzazione delle funzioni dei ministeri.
- Le /amministrazioni indipendenti/ sono distinte dalle politiche del ministero di riferimento.
  - Ad es., la Consob.
- La pubblicizzazione di soggetti privati era diffusa nel passato, e ha portato alla creazione di nuove PA.
  - Attualmente sarebbe impossibile, a causa della Costituzione.
  - Ad es., le "leggi crispine" che trasformavano le istituzioni di beneficenza private in soggetti pubblici.
  - Ad es., gli ordini professionali attualmente sono enti pubblici, inizialmente erano nati come istituzioni private, ma il legislatore ha deciso
** Riduzione della pluralità
- I ministeri sono stati accorpati.
- Molti enti pubblici sono stati privatizzati. Ad es., in fondazioni, etc.
- Spesso la privatizzazione è stata un'operazione solo formale.
** Atipicità
- Gli enti amministrativi sono largamente atipici.
- Ad es., le amministrazioni indipendenti sono regolate ciascuna dalla propria legge, ed i tentativi di creare una legge quadro sono falliti.
** Ambito soggettivo
- Il problema delle norme del diritto legislativo è il loro ambito di applicazione soggettiva.
- In tempi più recenti, il legislatore indica espressamente l'ambito di applicazione della norma.
- L'ISTAT pubblica un elenco annuale delle PA.
- Se l'ente pubblico non è indicato espressamente, vengono usati una serie di indizi:
  - Nomina pubblica degli organi.
  - Finanziamento pubblico.
    - Deve essere considerato insieme agli altri fattori.
    - Molti organi privati sono finanziati con fondi pubblici, ma non perdono la loro natura privata.
  - Poteri di vigilanza da parte del potere pubblico.
  - Esistenza necessaria.
    - L'ente pubblico serve a svolgere funzioni di interesse generale, e non può disporre liberamente in maniera autonoma della sua esistenza.
- Il legislatore europeo preferisce un'interpretazione sostanzialistica per definire l'ambito di applicazione delle norme.
* 2023-02-21
- Riassunto:
  - Il legislatore spesso rinvia alla legge sull'impiego nella PA, che include un elenco delle PA, o dal 2009, all'elenco delle PA individuate dall'ISTAT.
  - Se manca l'individuazione espressa, si fa ricorso agli indici di pubblicità.
** Classificazione degli enti pubblici:
- Enti pluri-funzionali e mono-funzionali: coincide con la distinzione fra enti territoriali ...
- Enti territoriali:
  - Sono costituzionalmente necessari.
  - Il territorio è un elemento costitutivo dell'ente.
  - Le collettività all'interno del territorio eleggono gli organi dell'ente.
  - Sono a fini generali, e si occupano del bene collettivo del territorio di competenza.
  - Ad es., il comune.
- Enti mono-funzionali:
  - Non si occupano di un territorio, ma di una funzione specifica.
  - Ad es., l'università.
- Enti a base associativa:
  - I partecipanti all'ente sono uguali fra di loro.
  - Ad es., le camere di commercio, le associazioni professionali.
- Enti a base istituzionale: i partecipanti sono organizzati in maniera gerarchica.
- Enti a fini strumentali: sono enti specializzati per svolgere una funzione di supporto per un altro ente.
- Enti indipendenti: non svolgono una funzione di supporto per altri enti.
- Ente non-economico: svolge solo funzioni pratiche o burocratiche.
- Ente economico:
  - Svolge attività di tipo industriale.
  - A seguito del processo di privatizzazione negli anni '90 sono stati trasformati in S.p.A.
  - Si applicano regole di carattere privatistico (ad es., le regole sull'impiego).
** Vicende degli enti pubblici
- Istituzione ed estinzione:
  - Richiedono l'uso di una norma.
  - Dibattito sugli enti inutili.
- Accorpamento:
  - Per raggiungere maggiori livello di efficienza ed economicità si procede all'unione di più enti in uno.
  - Ad es., la fusione di più comuni, la riduzione del numero di camere di commercio (camera di commercio della Romagna).
- Successione:
  - È una conseguenza dell'accorpamento.
  - Può essere funzionale o territoriale.
- Privatizzazione:
  - Un ente viene trasformato in un soggetto privato.
  - È formale se il soggetto privato rimane ad esistenza necessaria.
  - È sostanziale se il soggetto privato può decidere se smettere di esistere, oppure no.
  - Viene usata per esigenze di organizzazione interna, per ragioni di convenienza.
  - Le c.d. società legali esistono solo perché sono previste da una legge.
** Teoria dell'immedesimazione organica, organi
- Immedesimazione organica: gli atti ed effetti sono imputati all'ente, indipendentemente da quale suo organo siano svolti.
- Le norme di organizzazione di ogni figura soggettiva (legge o atti interni alla figura soggettiva) individuano quali atti giuridici possono essere adottati, e da quali organi.
- Ad es., all'interno dell'università le lezioni sono attività materiali, ma la valutazioni degli esami o il conferimento della laurea sono attività giuridiche.
- Attività di amministrazione:
  - Si divide in attiva, consultiva e di controllo.
  - Ogni attività viene svolta da uno o più organi.
- Riparto delle competenze:
  - È necessario determinare quale organo ha quali competenze.
  - Uno dei vizi degli atti è il fatto che sono stati adottati da un soggetto non competente.
* 2023-02-22
** Organi individuali e collegiali
- Il legislatore è libero di scegliere fra organi individuali e collegiali.
- *Organi individuali*:
  - Se prevale l'esigenza di celerità o informalità nelle scelte.
  - Ad es., il dirigente degli ospedali e aziende sanitarie, introdotti con la riforma della legislazione sanitaria degli anni '90.
- *Organi collegiali*:
  - L'organo è maggiormente idoneo a rappresentare interessi diversi, e potenzialmente in conflitto, o non coincidenti, e trovare una soluzione di compromesso.
  - Gli interessi diversi si possono avere sia nel caso in cui l'organo è eletto, sia nel caso in cui sia nominato. 
  - Gli organi collegiali possono essere scelti anche per maggiore ponderazione della valutazione, o valutazione da più soggetti che hanno preparazioni tecniche diverse.
  - Ad es., la commissione per la valutazione della laurea, la commissione per l'assunzione.
** Assunzione delle decisioni negli organi collegiali
- Garantisce il corretto funzionamento dell'organo.
- Prepara le *sedute* dell'organo collegiale, e definisce l'*ordine del giorno* (argomenti su cui i componenti del collegio deliberano).
- I componenti hanno *ampio diritto di accesso* alle informazioni utili per assumere le deliberazioni.
- Ogni organo ha le proprie regole sul *quorum* necessario per la decisione.
- *Quorum costitutivo*:
  - I *collegi perfetti* sono i collegi che possono funzionare solo con la totalità dei membri.
  - Si prevedono regole per la sostituzione dei membri che sono assenti, per evitare la paralisi dell'organo.
- *Quorum deliberativo*:
  - Astensione: può essere ignorata (chi si astiene non viene considerato ai fini del quorum deliberativo) o equiparata ad un voto negativo.
** Organi interni ed esterni
- *Esterni*: gli organi di amministrazione attiva compiono atti con rilevanza esterna.
- *Interni*: gli organi consultivi e di controllo compiono atti che hanno rilevanza solo all'interno.
** Organi permanenti e temporanei
- *Permanenti*: esistono stabilmente nella figura soggettiva.
- *Temporanei*:
  - Vengono creati ad hoc per una singola decisione, e vengono sciolti dopo che la decisione è stata presa.
  - Ad es., le commissioni di esame, di laurea, ecc.
- *Commissario ad acta*.
** Relazioni intersoggettive ed inter-organiche
*** Relazioni intersoggettive
- *Relazione di autonomia politica*:
  - Ogni figura soggettiva deve rispettare gli spazi di autonomia riconosciuti dalla Costituzione e dalle leggi alle altre figure soggettive.
  - Ad es., il comune è un ente autonomo rispetto agli altri enti territoriali.
  - In caso di *violazione* della sfera di autonomia, esistono dei rimedi.
  - Ad es., la *Corte Costituzionale* è anche giudice dei *conflitti di attribuzione tra Stato e Regioni*.
  - Se nell'esercizio del potere amministrativo Stato e Regioni invadono le reciproche sfere di competenza, la Corte può risolvere il conflitto.
  - Per gli *enti territoriali minori*, il *giudice amministrativo* è competente per i conflitti riguardanti l'esercizio del potere.
  - I rapporti intersoggettivi sono improntati al *principio di collaborazione e buona fede*.
  - Ad es., nel caso della costruzione di un'autostrada, la decisione interessa più comuni, e viene presa ad un livello più elevato.
- *Autonomia funzionale*:
  - Le *università* hanno una serie di prerogative, previste dalla Costituzione.
- *Relazione di indipendenza*:
  - Riguarda il rapporto fra *amministrazioni indipendenti* ed il resto della PA.
- *Rapporto di direzione*: ...
- *Rapporto di strumentalità*:
  - Ad es., le scuole sono enti pubblici, ma sono strettamente dipendenti dal Ministero dell'istruzione.
*** Relazioni interorganiche
- *Rapporto di gerarchia*:
  - È la relazione più stretta fra due organi, dove uno è gerarchicamente sovraordinato ad un altro organo.
  - L'organo sotto-ordinato ha una propria indipendenza, ed è comunque capace di emanare atti giuridici.
  - L'*organo sovraordinato ha pieni poteri*, e può impartire *ordini e direttive*, può *delegare funzioni*, può *avocare funzioni* e *annullare atti*.
  - Nel rapporto di direzione l'avocazione non è ammessa.
  - Il *ricorso gerarchico* è un ricorso rivolto al superiore gerarchico, per chiedere l'annullamento dell'atto emanato dall'inferiore.
  - L'annullamento può essere eseguito anche d'ufficio, in autotutela.
  - È utilizzato più raramente in tempi recenti.
* 2023-02-27
** Relazioni di controllo
- Potere di sostituzione [...].
- Esistono numerose norme che rappresentano l'implementazione concreta del potere di controllo.
** Relazioni temporanee
*** Delega
- L'imputazione organica degli effetti si ha in ordine al delegato.
- Il delegante ha dei poteri di controllo sul delegato.
- Nell'ambito della delega interorganica (non nella intersoggettiva, per esigenze di certezza del diritto), la giurisprudenza ammette la possibilità di esercitare poteri nell'ambito dei poteri delegati.
- Ad es., prima della riforma del titolo V lo Stato poteva delegare funzioni alle Regioni.
- Le deleghe intersoggettive devono essere previste dalla legge.
*** Avvalimento di uffici
- Lo Stato utilizza gli uffici dei Comuni per finalità di interesse statale.
- È un'alternativa più economica al posto di creare un nuovo ente.
*** Sostituzione
- Se un livello di governo non prende una decisione entro un termine perentorio, la competenza passa al livello di governo superiore.
- La norma che prevede il potere di sostituzione può istituire anche un organo straordinario, ad acta.
  - Ad es., il commissario straordinario che viene nominato quando vengono sciolti gli organi del Comune.
  - Assume tutti i poteri degli organi sciolti, ma solo per il tempo necessario per procedere alla loro riformazione.
** Uffici
- La nozione di "ufficio" fa parte della teoria dell'organizzazione.
- Specializzazione degli uffici: varia in base alla dimensione dell'ente, enti più grandi hanno uffici più specializzati.
- Tutti gli organi sono uffici, ma non tutti gli uffici sono organi.
** Rapporto d'ufficio
*** Base volontaria o obbligatoria
- Normalmente si forma su base volontaria, ma in casi eccezionali può essere su base obbligatoria.
- Ad es., il servizio militare limitava la libertà personale dei cittadini per un anno.
- Le giurie popolari sono a carattere obbligatorio, ma riguardano il potere giurisdizionale.
- Attualmente non sembra esistano casi di rapporti d'ufficio su base volontaria.
*** Rapporti d'ufficio professionale
- Se è un rapporto di lavoro dipendente.
- Il rapporto di impiego può essere pubblico o privato.
*** Rapporti d'ufficio onorari
- Si stabiliscono a seguito di *elezione* (uffici onorari a carattere elettivo) o *nomina politica*.
- Ad es., nel comune l'ufficio di sindaco, nelle università gli organi di vertice sono elettivi.
- Non esistono uffici onorari perenni, sono sempre *temporanei*.
- Si prevedono *limiti al rinnovo dei mandati* per evitare che si concentrino eccessivamente i poteri.
  - Normalmente si prevede il limite del secondo mandato, che idealmente porta la persona a comportarsi in maniera da essere rieletta nel secondo mandato.
  - In alcuni casi si prevede un "mandato secco", più lungo ma non rinnovabile, e può avere effetti controproducenti.
- La nomina pubblica non è puramente fiduciaria, ma la *legge può imporre requisiti* di professionalità, indipendenza, etc.
  - Nel secondo caso, chi è in possesso dei requisiti può sindacare la nomina davanti al giudice amministrativo.
- *Titolarità*: chi è titolare dell'ufficio.
- *Reggente*: chi sostituisce il titolare dell'ufficio che non può esercitare le proprie funzioni in maniera permanente.
- *Supplenti*: sono persone che assumono temporaneamente la titolarità dell'ufficio.
- *Sostituzione*: [...]
*** Doveri d'ufficio
- Sorgono dopo che si assume la titolarità dell'ufficio.
- Devono essere svolti con disciplina ed onore (?), e
- Il *dovere di esclusività* serve a garantire che le persone si dedichino alla PA.
- Esiste un *divieto generale di agire in conflitto di interessi*.
  - La *astensione* opera caso per caso.
  - La *inconferibilità o ineleggibilità* impedisce alla persona di essere scelta per una certa carica.
  - La *incompatibilità* impone alla persona di scegliere tra una carica pubblica, e quella che ha già.
- Sanzioni disciplinari: sono previste se la persona non rispetta i suoi doveri d'ufficio.
*** Proroga degli organi amministrativi
- Incostituzionalità della prassi amministrativa [...].
- Gli atti emanati da organi scaduti sono nulli [...].
